// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Token is an OAuth 2.0 token acquired from a token endpoint.
 */
export class Token {
    /**
     * Creates a new Token instance.
     * @param {Partial<Token>} [$$source = {}] - The source object to create the Token.
     */
    constructor($$source = {}) {
        if (!("AccessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AccessToken"] = "";
        }
        if (!("TokenType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TokenType"] = "";
        }
        if (!("ExpiresIn" in $$source)) {
            /**
             * ExpiresIn is the lifetime in seconds, 0 when the response omits it.
             * @member
             * @type {number}
             */
            this["ExpiresIn"] = 0;
        }
        if (!("Expiry" in $$source)) {
            /**
             * Expiry is the absolute expiry time derived from ExpiresIn plus the
             * acquisition time. It is zero when ExpiresIn is unknown.
             * @member
             * @type {string}
             */
            this["Expiry"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("RefreshToken" in $$source)) {
            /**
             * RefreshToken is the refresh token returned by the token endpoint,
             * empty for grants that do not issue one (e.g. Client Credentials).
             * @member
             * @type {string}
             */
            this["RefreshToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Token instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Token}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Token(/** @type {Partial<Token>} */($$parsedSource));
    }
}
