// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExpiryStatus reports exp/nbf/iat-derived validity at decode time.
 */
export class ExpiryStatus {
    /**
     * Creates a new ExpiryStatus instance.
     * @param {Partial<ExpiryStatus>} [$$source = {}] - The source object to create the ExpiryStatus.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * expired|not_yet_valid|valid|no_expiry
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("remaining" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remaining"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["exp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["nbf"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["iat"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExpiryStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExpiryStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExpiryStatus(/** @type {Partial<ExpiryStatus>} */($$parsedSource));
    }
}
