// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Theme defines a shareable UI theme. Tokens are CSS variable values
 * without the -- prefix, e.g. Tokens["primary"] = "#c93517".
 */
export class Theme {
    /**
     * Creates a new Theme instance.
     * @param {Partial<Theme>} [$$source = {}] - The source object to create the Theme.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("appearance" in $$source)) {
            /**
             * light | dark
             * @member
             * @type {string}
             */
            this["appearance"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["tokens"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Theme}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField3_0($$parsedSource["tokens"]);
        }
        return new Theme(/** @type {Partial<Theme>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
