// Reqly - A local-first, Git-native API development environment.
// Copyright 2026 It's Satyajit
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/grpc/testsrv/testapi.proto

package testsrv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_internal_grpc_testsrv_testapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_testsrv_testapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_testsrv_testapi_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_internal_grpc_testsrv_testapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_testsrv_testapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_testsrv_testapi_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EchoResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EchoResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_internal_grpc_testsrv_testapi_proto protoreflect.FileDescriptor

const file_internal_grpc_testsrv_testapi_proto_rawDesc = "" +
	"\n" +
	"#internal/grpc/testsrv/testapi.proto\x12\rreqly.test.v1\"\x9c\x01\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12>\n" +
	"\x06labels\x18\x02 \x03(\v2&.reqly.test.v1.EchoRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\fEchoResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12?\n" +
	"\x06labels\x18\x03 \x03(\v2'.reqly.test.v1.EchoResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x97\x01\n" +
	"\vEchoService\x12?\n" +
	"\x04Echo\x12\x1a.reqly.test.v1.EchoRequest\x1a\x1b.reqly.test.v1.EchoResponse\x12G\n" +
	"\n" +
	"StreamEcho\x12\x1a.reqly.test.v1.EchoRequest\x1a\x1b.reqly.test.v1.EchoResponse0\x01B=Z;github.com/Its-Satyajit/reqly/internal/grpc/testsrv;testsrvb\x06proto3"

var (
	file_internal_grpc_testsrv_testapi_proto_rawDescOnce sync.Once
	file_internal_grpc_testsrv_testapi_proto_rawDescData []byte
)

func file_internal_grpc_testsrv_testapi_proto_rawDescGZIP() []byte {
	file_internal_grpc_testsrv_testapi_proto_rawDescOnce.Do(func() {
		file_internal_grpc_testsrv_testapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_testsrv_testapi_proto_rawDesc), len(file_internal_grpc_testsrv_testapi_proto_rawDesc)))
	})
	return file_internal_grpc_testsrv_testapi_proto_rawDescData
}

var file_internal_grpc_testsrv_testapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_testsrv_testapi_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: reqly.test.v1.EchoRequest
	(*EchoResponse)(nil), // 1: reqly.test.v1.EchoResponse
	nil,                  // 2: reqly.test.v1.EchoRequest.LabelsEntry
	nil,                  // 3: reqly.test.v1.EchoResponse.LabelsEntry
}
var file_internal_grpc_testsrv_testapi_proto_depIdxs = []int32{
	2, // 0: reqly.test.v1.EchoRequest.labels:type_name -> reqly.test.v1.EchoRequest.LabelsEntry
	3, // 1: reqly.test.v1.EchoResponse.labels:type_name -> reqly.test.v1.EchoResponse.LabelsEntry
	0, // 2: reqly.test.v1.EchoService.Echo:input_type -> reqly.test.v1.EchoRequest
	0, // 3: reqly.test.v1.EchoService.StreamEcho:input_type -> reqly.test.v1.EchoRequest
	1, // 4: reqly.test.v1.EchoService.Echo:output_type -> reqly.test.v1.EchoResponse
	1, // 5: reqly.test.v1.EchoService.StreamEcho:output_type -> reqly.test.v1.EchoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_testsrv_testapi_proto_init() }
func file_internal_grpc_testsrv_testapi_proto_init() {
	if File_internal_grpc_testsrv_testapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_testsrv_testapi_proto_rawDesc), len(file_internal_grpc_testsrv_testapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_testsrv_testapi_proto_goTypes,
		DependencyIndexes: file_internal_grpc_testsrv_testapi_proto_depIdxs,
		MessageInfos:      file_internal_grpc_testsrv_testapi_proto_msgTypes,
	}.Build()
	File_internal_grpc_testsrv_testapi_proto = out.File
	file_internal_grpc_testsrv_testapi_proto_goTypes = nil
	file_internal_grpc_testsrv_testapi_proto_depIdxs = nil
}
