// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Change {
    /**
     * Creates a new Change instance.
     * @param {Partial<Change>} [$$source = {}] - The source object to create the Change.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "create", "update", "delete"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["path"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["to"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Severity classifies OpenAPI changes ("breaking", "addition", "info");
             * populated by WithSeverity, empty for raw JSON diffs.
             * @member
             * @type {string | undefined}
             */
            this["severity"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Change}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField1_0($$parsedSource["path"]);
        }
        return new Change(/** @type {Partial<Change>} */($$parsedSource));
    }
}

/**
 * DiffResult holds structural diff information.
 */
export class DiffResult {
    /**
     * Creates a new DiffResult instance.
     * @param {Partial<DiffResult>} [$$source = {}] - The source object to create the DiffResult.
     */
    constructor($$source = {}) {
        if (!("hasChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChanges"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Change[] | undefined}
             */
            this["changes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField1_0($$parsedSource["changes"]);
        }
        return new DiffResult(/** @type {Partial<DiffResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Change.createFrom;
const $$createType2 = $Create.Array($$createType1);
