// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Category classifies which part of an import a report entry concerns.
 * @readonly
 * @enum {string}
 */
export const Category = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CategoryAuth: "auth",
    CategoryScript: "script",
    CategoryBody: "body",
    CategoryEnvironment: "environment",
    CategorySchema: "schema",
    CategoryOther: "other",
};

/**
 * Format identifies which import format a payload represents, as determined
 * by Detect from content alone.
 * @readonly
 * @enum {string}
 */
export const Format = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FormatCurl: "curl",
    FormatOpenAPI: "openapi",
    FormatHAR: "har",
    FormatPostman: "postman",
    FormatInsomnia: "insomnia",
    FormatBruno: "bruno",
};

/**
 * ImportReport is the structured record of how an import degraded its source.
 * Every parser returns one in place of the former []string warnings; rendering
 * belongs to callers (the CLI groups by category, desktop renders later).
 */
export class ImportReport {
    /**
     * Creates a new ImportReport instance.
     * @param {Partial<ImportReport>} [$$source = {}] - The source object to create the ImportReport.
     */
    constructor($$source = {}) {
        if (!("importer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["importer"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {ReportEntry[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportReport}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new ImportReport(/** @type {Partial<ImportReport>} */($$parsedSource));
    }
}

/**
 * ReportEntry is one structured degradation, skip, or translation record.
 * ItemPath locates the source item (request/folder/environment name or
 * positional label such as "entry 3"); Message carries the same human-readable
 * text the free-text warning strings used before reports existed.
 */
export class ReportEntry {
    /**
     * Creates a new ReportEntry instance.
     * @param {Partial<ReportEntry>} [$$source = {}] - The source object to create the ReportEntry.
     */
    constructor($$source = {}) {
        if (!("itemPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["itemPath"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {Category}
             */
            this["category"] = Category.$zero;
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportEntry(/** @type {Partial<ReportEntry>} */($$parsedSource));
    }
}

/**
 * Severity records what happened to the source feature: it was mapped onto
 * Reqly-native form, degraded but imported, or skipped entirely.
 * @readonly
 * @enum {string}
 */
export const Severity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SeverityTranslated: "translated",
    SeverityWarned: "warned",
    SeverityDropped: "dropped",
};

// Private type creation functions
const $$createType0 = ReportEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
