// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Issue is a single validation finding.
 */
export class Issue {
    /**
     * Creates a new Issue instance.
     * @param {Partial<Issue>} [$$source = {}] - The source object to create the Issue.
     */
    constructor($$source = {}) {
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Issue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Issue(/** @type {Partial<Issue>} */($$parsedSource));
    }
}

/**
 * KeyDiff describes a single key-level change between two environments.
 */
export class KeyDiff {
    /**
     * Creates a new KeyDiff instance.
     * @param {Partial<KeyDiff>} [$$source = {}] - The source object to create the KeyDiff.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name is the variable or secret key.
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * Status is one of the Status* constants: added, removed, or changed.
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * Kind is one of the Kind* constants: variable or secret.
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * From is the value in the first environment (secrets masked).
             * @member
             * @type {string}
             */
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            /**
             * To is the value in the second environment (secrets masked).
             * @member
             * @type {string}
             */
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KeyDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyDiff(/** @type {Partial<KeyDiff>} */($$parsedSource));
    }
}

/**
 * Severity classifies a validation finding.
 * @readonly
 * @enum {string}
 */
export const Severity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Validation severities.
     */
    SeverityError: "error",
    SeverityWarning: "warning",
};
