// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Response models an executed API response: status, headers, body, timing,
 * and size. It is shared by the Desktop, CLI, and MCP front-ends.
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("StatusCode" in $$source)) {
            /**
             * StatusCode is the HTTP status code (e.g. 200).
             * @member
             * @type {number}
             */
            this["StatusCode"] = 0;
        }
        if (!("StatusText" in $$source)) {
            /**
             * StatusText is the status text (e.g. "OK").
             * @member
             * @type {string}
             */
            this["StatusText"] = "";
        }
        if (!("Proto" in $$source)) {
            /**
             * Proto is the HTTP protocol version (e.g. "HTTP/1.1").
             * @member
             * @type {string}
             */
            this["Proto"] = "";
        }
        if (!("Headers" in $$source)) {
            /**
             * Headers are the response headers.
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["Headers"] = {};
        }
        if (!("Body" in $$source)) {
            /**
             * Body is the raw response body.
             * @member
             * @type {string}
             */
            this["Body"] = "";
        }
        if (!("Duration" in $$source)) {
            /**
             * Duration is the total request duration.
             * @member
             * @type {time$0.Duration}
             */
            this["Duration"] = time$0.Duration.$zero;
        }
        if (!("Size" in $$source)) {
            /**
             * Size is the body size in bytes.
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }
        if (!("Attempts" in $$source)) {
            /**
             * Attempts is the number of sends this response took, including retries
             * (1 means the request succeeded or failed on its first attempt).
             * @member
             * @type {number}
             */
            this["Attempts"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Timings holds network phase durations (ms) for timeline debugging (M52).
             * @member
             * @type {Timings | null | undefined}
             */
            this["timings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $Create.ByteSlice;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Headers" in $$parsedSource) {
            $$parsedSource["Headers"] = $$createField3_0($$parsedSource["Headers"]);
        }
        if ("Body" in $$parsedSource) {
            $$parsedSource["Body"] = $$createField4_0($$parsedSource["Body"]);
        }
        if ("timings" in $$parsedSource) {
            $$parsedSource["timings"] = $$createField8_0($$parsedSource["timings"]);
        }
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

/**
 * Timings holds phase durations for the request timeline (DNS/connect/TLS/…).
 */
export class Timings {
    /**
     * Creates a new Timings instance.
     * @param {Partial<Timings>} [$$source = {}] - The source object to create the Timings.
     */
    constructor($$source = {}) {
        if (!("dns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dns"] = 0;
        }
        if (!("connect" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connect"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tls"] = 0;
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["request"] = 0;
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["server"] = 0;
        }
        if (!("response" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["response"] = 0;
        }
        if (!("transfer" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transfer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Timings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Timings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Timings(/** @type {Partial<Timings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = Timings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
