// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RBAC is a local role-based access control config.
 * Stored as .reqly/rbac.yaml (0600), Git-native when committed.
 */
export class RBAC {
    /**
     * Creates a new RBAC instance.
     * @param {Partial<RBAC>} [$$source = {}] - The source object to create the RBAC.
     */
    constructor($$source = {}) {
        if (!("roles" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: Role }}
             */
            this["roles"] = {};
        }
        if (!("userRoles" in $$source)) {
            /**
             * user -> role
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["userRoles"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RBAC instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RBAC}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField0_0($$parsedSource["roles"]);
        }
        if ("userRoles" in $$parsedSource) {
            $$parsedSource["userRoles"] = $$createField1_0($$parsedSource["userRoles"]);
        }
        return new RBAC(/** @type {Partial<RBAC>} */($$parsedSource));
    }
}

/**
 * Role defines a set of permissions.
 */
export class Role {
    /**
     * Creates a new Role instance.
     * @param {Partial<Role>} [$$source = {}] - The source object to create the Role.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["permissions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Role instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Role}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField1_0($$parsedSource["permissions"]);
        }
        return new Role(/** @type {Partial<Role>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Role.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
