// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is a Wails v3 service exposing the Go core to the frontend.
 * It should stay thin: business logic belongs in the Go core (internal/core).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../../../internal/audit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../../../internal/auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collab$0 from "../../../internal/collab/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffing$0 from "../../../internal/diffing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as graphql$0 from "../../../internal/graphql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grpc$0 from "../../../internal/grpc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../../../internal/history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as policy$0 from "../../../internal/policy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rbac$0 from "../../../internal/rbac/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../../internal/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scim$0 from "../../../internal/scim/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as theme$0 from "../../../internal/theme/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "../../../internal/workflow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AuditAdd appends an entry and returns it.
 * @param {string} action
 * @param {string} resource
 * @param {string} details
 * @returns {$CancellablePromise<audit$0.Entry>}
 */
export function AuditAdd(action, resource, details) {
    return $Call.ByID(1997671940, action, resource, details).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AuditClear truncates the log.
 * @returns {$CancellablePromise<void>}
 */
export function AuditClear() {
    return $Call.ByID(1245961554);
}

/**
 * AuditExport returns the audit log as JSONL string for downloads.
 * @returns {$CancellablePromise<string>}
 */
export function AuditExport() {
    return $Call.ByID(595648611);
}

/**
 * AuditList returns audit entries for the current workspace.
 * @returns {$CancellablePromise<audit$0.Entry[]>}
 */
export function AuditList() {
    return $Call.ByID(2976150193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {{ [_ in string]?: string }} config
 * @param {string} flow
 * @returns {$CancellablePromise<auth$0.Token | null>}
 */
export function AuthLogin(config, flow) {
    return $Call.ByID(763009485, config, flow).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AuthLogout clears every cached OAuth token for the app's workspace and
 * returns how many were removed.
 * @returns {$CancellablePromise<number>}
 */
export function AuthLogout() {
    return $Call.ByID(508720950);
}

/**
 * AuthStatus lists the cached OAuth tokens for the app's workspace with
 * masked values, plus the active store backend.
 * @returns {$CancellablePromise<$models.AuthStatusResponse | null>}
 */
export function AuthStatus() {
    return $Call.ByID(1698985218).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * AutomationRun executes an automation YAML string once (ignoring its interval)
 * and returns the workflow report. Desktop parity for `reqly automation run`.
 * @param {string} yamlStr
 * @returns {$CancellablePromise<workflow$0.WorkflowReport | null>}
 */
export function AutomationRun(yamlStr) {
    return $Call.ByID(2613900714, yamlStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * CancelSend aborts the in-flight send registered under sendID. An unknown or
 * already-finished id is a silent no-op: the UI may press Stop after the
 * response arrived.
 * @param {string} sendID
 * @returns {$CancellablePromise<void>}
 */
export function CancelSend(sendID) {
    return $Call.ByID(1736959094, sendID);
}

/**
 * CollabAdd adds a collaborator.
 * @param {string} user
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function CollabAdd(user, role) {
    return $Call.ByID(4074512402, user, role);
}

/**
 * CollabList returns collaborators for the workspace.
 * @returns {$CancellablePromise<collab$0.Collaborator[]>}
 */
export function CollabList() {
    return $Call.ByID(3622445647).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * CollabRemove removes a collaborator.
 * @param {string} user
 * @returns {$CancellablePromise<void>}
 */
export function CollabRemove(user) {
    return $Call.ByID(1276384075, user);
}

/**
 * CollabServe starts a self-hosted collaboration server and returns its URL.
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function CollabServe(port) {
    return $Call.ByID(2154074598, port);
}

/**
 * CookieClear clears cookies.
 * @param {string | null} env
 * @returns {$CancellablePromise<void>}
 */
export function CookieClear(env) {
    return $Call.ByID(2914920517, env);
}

/**
 * CookieDelete deletes one cookie.
 * @param {string} name
 * @param {string} domain
 * @param {string} path
 * @param {string} env
 * @returns {$CancellablePromise<void>}
 */
export function CookieDelete(name, domain, path, env) {
    return $Call.ByID(3982028771, name, domain, path, env);
}

/**
 * CookieList lists cookies for env.
 * @param {string} env
 * @returns {$CancellablePromise<history$0.Cookie[]>}
 */
export function CookieList(env) {
    return $Call.ByID(2511501632, env).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * DeliverCustomSchemeCallback feeds a reqly:// (or other registered) deep
 * link into the waiting authorization-code flow. The host calls this when the
 * OS delivers a registered URL to the app.
 * @param {string} uri
 * @returns {$CancellablePromise<void>}
 */
export function DeliverCustomSchemeCallback(uri) {
    return $Call.ByID(2849187156, uri);
}

/**
 * Detect sniffs content and reports which import format it represents, so
 * the dialog can badge the detected format as the user types or drops a
 * file. Advisory only — Import's FormatHint overrides it.
 * @param {string} content
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function Detect(content) {
    return $Call.ByID(4184603341, content);
}

/**
 * DiffJSONText diffs two raw JSON/YAML documents pasted in the dialog —
 * YAML input is converted before the structural comparison.
 * @param {string} a
 * @param {string} b
 * @returns {$CancellablePromise<diffing$0.DiffResult | null>}
 */
export function DiffJSONText(a, b) {
    return $Call.ByID(1755610296, a, b).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * DiffResponses compares two history entries' response bodies structurally
 * and returns both entries' metadata for a side-by-side header.
 * @param {string} idA
 * @param {string} idB
 * @returns {$CancellablePromise<$models.ResponseDiffResult | null>}
 */
export function DiffResponses(idA, idB) {
    return $Call.ByID(4294335435, idA, idB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * DiffSpecs diffs two OpenAPI specs (workspace-relative or absolute paths)
 * and classifies every change by severity.
 * @param {string} pathA
 * @param {string} pathB
 * @returns {$CancellablePromise<$models.SpecDiffResult | null>}
 */
export function DiffSpecs(pathA, pathB) {
    return $Call.ByID(3619694931, pathA, pathB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * DocsGenerate renders Markdown documentation (index.md + one file per
 * collection) from the open workspace into `<root>/.reqly/docs/<name>/` —
 * outside Git, like exports — and returns every file for in-app preview.
 * @param {$models.DocsGenerateRequest} req
 * @returns {$CancellablePromise<$models.DocsResult | null>}
 */
export function DocsGenerate(req) {
    return $Call.ByID(4233228850, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * EnvCreate writes a new environment (name + optional description +
 * variables) to disk. Errors on an empty/unsafe name or a duplicate.
 * @param {string} name
 * @param {string} description
 * @param {{ [_ in string]?: string }} variables
 * @returns {$CancellablePromise<void>}
 */
export function EnvCreate(name, description, variables) {
    return $Call.ByID(3043377989, name, description, variables);
}

/**
 * EnvCrossValidate checks variable-key consistency across every environment
 * in the workspace: a key present in some but missing in others is a gap.
 * @returns {$CancellablePromise<$models.CrossEnvGap[]>}
 */
export function EnvCrossValidate() {
    return $Call.ByID(1039405853).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * EnvDelete removes an environment file, clearing the descriptor's active
 * selection when the deleted environment was active.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnvDelete(name) {
    return $Call.ByID(2408031650, name);
}

/**
 * EnvDiff compares two environments by name (masked secrets).
 * @param {string} envA
 * @param {string} envB
 * @returns {$CancellablePromise<$models.EnvDiffResult | null>}
 */
export function EnvDiff(envA, envB) {
    return $Call.ByID(2285575762, envA, envB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * EnvList lists the workspace's environments plus the active one. Secret
 * values never cross the bridge — only their names are returned.
 * @returns {$CancellablePromise<core$0.EnvListResponse | null>}
 */
export function EnvList() {
    return $Call.ByID(3532091529).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * EnvRead returns a single environment by name, without secret values.
 * @param {string} name
 * @returns {$CancellablePromise<core$0.Environment | null>}
 */
export function EnvRead(name) {
    return $Call.ByID(482078317, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * EnvSetActive persists name as the workspace's active environment in the
 * descriptor. An empty name clears the selection.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function EnvSetActive(name) {
    return $Call.ByID(2732572757, name);
}

/**
 * EnvUpdate rewrites an existing environment's description and variables,
 * preserving its secrets on disk.
 * @param {string} name
 * @param {string} description
 * @param {{ [_ in string]?: string }} variables
 * @returns {$CancellablePromise<void>}
 */
export function EnvUpdate(name, description, variables) {
    return $Call.ByID(2753025084, name, description, variables);
}

/**
 * EnvUpdateSecrets changes an environment's secrets: `values` holds only the
 * secrets the user changed; `remove` names secrets to delete. Existing secret
 * values never leave the disk.
 * @param {string} name
 * @param {{ [_ in string]?: string }} values
 * @param {string[]} remove
 * @returns {$CancellablePromise<void>}
 */
export function EnvUpdateSecrets(name, values, remove) {
    return $Call.ByID(2572691433, name, values, remove);
}

/**
 * EnvValidate runs `reqly env validate` for one environment, scanning the
 * workspace for undefined {{variable}} references.
 * @param {string} name
 * @returns {$CancellablePromise<$models.EnvValidateResult | null>}
 */
export function EnvValidate(name) {
    return $Call.ByID(598183091, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * Export writes a shareable artifact derived from the open workspace into
 * `<root>/.reqly/exports/` — outside Git, next to history.db. Postman and
 * OpenAPI flatten every request exactly like the CLI; HAR synthesizes from
 * history with secrets masked; workspace copies descriptors + request files
 * via SaveWorkspace.
 * @param {$models.ExportRequest} req
 * @returns {$CancellablePromise<$models.ExportResult | null>}
 */
export function Export(req) {
    return $Call.ByID(331948616, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * GitCommit stages files and commits.
 * @param {string} message
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function GitCommit(message, files) {
    return $Call.ByID(992901511, message, files);
}

/**
 * GitDiff returns git diff (staged when staged true).
 * @param {boolean} staged
 * @returns {$CancellablePromise<string>}
 */
export function GitDiff(staged) {
    return $Call.ByID(334017009, staged);
}

/**
 * GitLog returns recent log lines.
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<string[]>}
 */
export function GitLog(limit, offset) {
    return $Call.ByID(2576985120, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GitStatus returns porcelain status lines.
 * @returns {$CancellablePromise<string[]>}
 */
export function GitStatus() {
    return $Call.ByID(3117326292).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GraphqlIntrospect runs the standard introspection query against an endpoint
 * and returns the parsed schema — identical fidelity to `reqly graphql
 * introspect`. Headers carry auth; timeout is in seconds (0 = none).
 * @param {string} endpoint
 * @param {$models.RealtimeHeader[]} headers
 * @param {number} timeoutSec
 * @returns {$CancellablePromise<graphql$0.Schema | null>}
 */
export function GraphqlIntrospect(endpoint, headers, timeoutSec) {
    return $Call.ByID(1478759704, endpoint, headers, timeoutSec).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GrpcCancel tears down one streaming session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function GrpcCancel(sessionID) {
    return $Call.ByID(288515752, sessionID);
}

/**
 * GrpcInvoke performs one unary gRPC call.
 * @param {$models.GrpcInvokeRequest} req
 * @returns {$CancellablePromise<grpc$0.Result | null>}
 */
export function GrpcInvoke(req) {
    return $Call.ByID(2633117370, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * GrpcServices discovers services/methods via reflection (or protoFiles).
 * @param {$models.GrpcServicesRequest} req
 * @returns {$CancellablePromise<grpc$0.Service[]>}
 */
export function GrpcServices(req) {
    return $Call.ByID(2634095158, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * GrpcStream opens a server-streaming call; messages stream on
 * reqly.grpc.<sessionID> until the server closes or GrpcCancel is called.
 * @param {$models.GrpcInvokeRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function GrpcStream(req) {
    return $Call.ByID(3513302434, req);
}

/**
 * HistoryClear clears history.
 * @param {string | null} env
 * @returns {$CancellablePromise<void>}
 */
export function HistoryClear(env) {
    return $Call.ByID(869791203, env);
}

/**
 * HistoryList returns masked history entries.
 * @param {number} limit
 * @param {number} offset
 * @param {string} status
 * @param {string} env
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function HistoryList(limit, offset, status, env) {
    return $Call.ByID(539796886, limit, offset, status, env).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * HistoryReplay replays a stored entry verbatim.
 * @param {string} id
 * @returns {$CancellablePromise<core$0.SendResponse | null>}
 */
export function HistoryReplay(id) {
    return $Call.ByID(2268652949, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * HistoryReplayWithVars replays a stored entry with variable overrides layered via variables.Set.
 * Vars are interpolated into URL/headers/body at build time; history entry itself is not mutated.
 * @param {string} id
 * @param {{ [_ in string]?: string }} vars
 * @returns {$CancellablePromise<core$0.SendResponse | null>}
 */
export function HistoryReplayWithVars(id, vars) {
    return $Call.ByID(838946835, id, vars).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * HistorySearch searches via FTS.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function HistorySearch(query, limit) {
    return $Call.ByID(1022436690, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * HistoryShow returns one masked entry.
 * @param {string} id
 * @returns {$CancellablePromise<history$0.Entry | null>}
 */
export function HistoryShow(id) {
    return $Call.ByID(1884836015, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * Import parses and optionally commits an import through the shared importer
 * core — identical fidelity to `reqly import`. Detection runs on content
 * alone; a valid FormatHint wins over detection. Dry-run never touches the
 * filesystem. Commit writes a fresh folder under the workspace root named by
 * TargetDir (sanitized) or the collection title, and fails fast when it
 * already exists — imports never silently merge into an existing workspace.
 * @param {$models.ImportRequest} req
 * @returns {$CancellablePromise<$models.ImportResult | null>}
 */
export function Import(req) {
    return $Call.ByID(1882279671, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * JwtDecode decodes a JWT offline (no verification) — identical fidelity to
 * `reqly jwt decode`, including expiry status computed at decode time.
 * @param {string} token
 * @returns {$CancellablePromise<$models.JwtTokenView | null>}
 */
export function JwtDecode(token) {
    return $Call.ByID(448068869, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * JwtFromAuthHeader extracts a bearer token from an Authorization header
 * value ("Bearer eyJ…") — used by the inspector's auto-capture.
 * @param {string} value
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function JwtFromAuthHeader(value) {
    return $Call.ByID(622402204, value);
}

/**
 * MockStart spins up the shared mock server. A running server is stopped
 * first — the panel owns exactly one instance.
 * @param {$models.MockStartRequest} req
 * @returns {$CancellablePromise<$models.MockStatus | null>}
 */
export function MockStart(req) {
    return $Call.ByID(479727240, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * MockStatusSnapshot reports the current server state.
 * @returns {$CancellablePromise<$models.MockStatus | null>}
 */
export function MockStatusSnapshot() {
    return $Call.ByID(2166148594).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * MockStop gracefully shuts down the running mock server; stopping a stopped
 * server is a no-op.
 * @returns {$CancellablePromise<void>}
 */
export function MockStop() {
    return $Call.ByID(3035005164);
}

/**
 * OpenapiExplore parses a spec and returns every operation with inline
 * request/response schema views.
 * @param {string} specPath
 * @returns {$CancellablePromise<$models.OpenapiExploreResult | null>}
 */
export function OpenapiExplore(specPath) {
    return $Call.ByID(3128899481, specPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * OpenapiGenerateRequests renders native request files for the selected
 * operations into `<workspace>/collections/<dirName>` — identical rendering
 * to `reqly openapi generate`.
 * @param {string} specPath
 * @param {$models.OpenapiGenerateSelection[]} selections
 * @param {string} dirName
 * @returns {$CancellablePromise<$models.OpenapiGenerateResult | null>}
 */
export function OpenapiGenerateRequests(specPath, selections, dirName) {
    return $Call.ByID(2012428711, specPath, selections, dirName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * PerfRun executes a perf load for the request file at specPath (workspace-relative).
 * @param {string} specPath
 * @param {number} rps
 * @param {number} durationMs
 * @param {number} concurrency
 * @returns {$CancellablePromise<$models.PerfRunResult | null>}
 */
export function PerfRun(specPath, rps, durationMs, concurrency) {
    return $Call.ByID(1309917298, specPath, rps, durationMs, concurrency).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * PolicyEnforce checks if an action is allowed.
 * @param {string} action
 * @param {string} resource
 * @returns {$CancellablePromise<void>}
 */
export function PolicyEnforce(action, resource) {
    return $Call.ByID(3456645066, action, resource);
}

/**
 * PolicyGet returns the current policy for the workspace.
 * @returns {$CancellablePromise<policy$0.Policy>}
 */
export function PolicyGet() {
    return $Call.ByID(3325423704).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType56($result);
    }));
}

/**
 * PolicySave writes a policy for the workspace (0600).
 * @param {policy$0.Policy} p
 * @returns {$CancellablePromise<void>}
 */
export function PolicySave(p) {
    return $Call.ByID(270028553, p);
}

/**
 * RBACCheck checks if a user can perform an action.
 * @param {string} user
 * @param {string} action
 * @param {string} resource
 * @returns {$CancellablePromise<void>}
 */
export function RBACCheck(user, action, resource) {
    return $Call.ByID(3114920474, user, action, resource);
}

/**
 * RBACGet returns the full RBAC config.
 * @returns {$CancellablePromise<rbac$0.RBAC>}
 */
export function RBACGet() {
    return $Call.ByID(125780998).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * RBACList returns RBAC roles for the workspace.
 * @returns {$CancellablePromise<string[]>}
 */
export function RBACList() {
    return $Call.ByID(509106470).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * RealtimeClose tears down one session by id. Closing an unknown or already
 * closed session is a no-op.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function RealtimeClose(sessionID) {
    return $Call.ByID(1441593745, sessionID);
}

/**
 * RealtimeOpen dials the endpoint and starts streaming frames to
 * `reqly.realtime.<sessionID>`. It returns after the handshake resolves:
 * connect errors surface here, stream errors arrive as events.
 * @param {$models.RealtimeOpenRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function RealtimeOpen(req) {
    return $Call.ByID(633971447, req);
}

/**
 * RealtimeSend writes one text frame on an open WebSocket session.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function RealtimeSend(sessionID, data) {
    return $Call.ByID(730188973, sessionID, data);
}

/**
 * RealtimeSendBinary writes one binary frame on an open WebSocket session.
 * The payload arrives base64-encoded from the webview and is echoed back into
 * the inspector the same way inbound binary frames are rendered.
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function RealtimeSendBinary(sessionID, data) {
    return $Call.ByID(2986756372, sessionID, data);
}

/**
 * RunExportReport serializes the last collection run as JSON or JUnit XML
 * into `<root>/.reqly/exports/` and returns the rendered text.
 * @param {string} format
 * @param {$models.RunReportExportInput} $in
 * @returns {$CancellablePromise<$models.RunExportResult | null>}
 */
export function RunExportReport(format, $in) {
    return $Call.ByID(2244587823, format, $in).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * RunnerCancel cancels nothing yet — runner cancellation is deferred; the
 * method exists so the frontend can call it unconditionally.
 * @param {string} runID
 * @returns {$CancellablePromise<void>}
 */
export function RunnerCancel(runID) {
    return $Call.ByID(1644608566, runID);
}

/**
 * RunnerStart launches an async run. Steps stream on
 * `reqly.runner.<runId>.step` and the summary on `.done` — same shape as the
 * collection Run View's event protocol.
 * @param {$models.RunnerRunRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function RunnerStart(req) {
    return $Call.ByID(4183376696, req);
}

/**
 * SCIMCreateUser creates a SCIM user (in-memory for M73).
 * @param {string} username
 * @param {string} email
 * @returns {$CancellablePromise<scim$0.User>}
 */
export function SCIMCreateUser(username, email) {
    return $Call.ByID(1819736929, username, email).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType60($result);
    }));
}

/**
 * SCIMListUsers lists SCIM users.
 * @returns {$CancellablePromise<scim$0.User[]>}
 */
export function SCIMListUsers() {
    return $Call.ByID(1874858414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * SSOValidate validates an OIDC token for the desktop.
 * @param {string} issuer
 * @param {string} clientID
 * @param {string} token
 * @param {string} secret
 * @returns {$CancellablePromise<void>}
 */
export function SSOValidate(issuer, clientID, token, secret) {
    return $Call.ByID(2843158715, issuer, clientID, token, secret);
}

/**
 * SendRequest executes an HTTP request through the shared execution pipeline
 * (ADR 0025): environment precedence, variable layering, token caching,
 * Cookie Jar attachment, retry handling, history recording, and masking all
 * live behind core.RequestService.Run — identical fidelity to the CLI. For
 * file-backed sends (RequestPath set) the request is re-resolved against the
 * live draft so inherited fields reflect the current container chain;
 * otherwise it is sent as-is (scratchpad).
 * @param {request$0.Request} r
 * @param {$models.SendOptions} opts
 * @returns {$CancellablePromise<core$0.SendResponse | null>}
 */
export function SendRequest(r, opts) {
    return $Call.ByID(249016537, r, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * SpecRead returns the raw content of a spec file at a workspace-relative or absolute path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function SpecRead(path) {
    return $Call.ByID(3946302797, path);
}

/**
 * SpecSave writes content to a spec file atomically with 0644 permissions.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SpecSave(path, content) {
    return $Call.ByID(3782839280, path, content);
}

/**
 * TestFileRead loads a test file's raw text for the editor. Paths may be
 * workspace-relative or absolute.
 * @param {string} path
 * @returns {$CancellablePromise<$models.TestFileContent | null>}
 */
export function TestFileRead(path) {
    return $Call.ByID(1475609536, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * TestFileWrite validates content through the shared parser before writing —
 * a broken suite never reaches disk.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function TestFileWrite(path, content) {
    return $Call.ByID(1944196667, path, content);
}

/**
 * TestRun executes the request defined in the test file and evaluates every
 * assertion — identical fidelity to `reqly test`, including secret masking
 * via the shared pipeline.
 * @param {$models.TestRunRequest} req
 * @returns {$CancellablePromise<$models.TestRunResult | null>}
 */
export function TestRun(req) {
    return $Call.ByID(3292854283, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * TestsList walks the workspace for *.reqly-test.{yaml,yml,json} files —
 * the same on-disk contract as `reqly test`.
 * @returns {$CancellablePromise<$models.TestFileRef[]>}
 */
export function TestsList() {
    return $Call.ByID(2285224867).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType67($result);
    }));
}

/**
 * ThemeExport returns the YAML for a theme by id.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ThemeExport(id) {
    return $Call.ByID(2626613217, id);
}

/**
 * ThemeImport parses and validates a theme YAML/JSON string and returns its CSS.
 * @param {string} yamlStr
 * @returns {$CancellablePromise<string>}
 */
export function ThemeImport(yamlStr) {
    return $Call.ByID(2694246482, yamlStr);
}

/**
 * ThemeList returns built-in themes for the desktop theme picker.
 * @returns {$CancellablePromise<theme$0.Theme[]>}
 */
export function ThemeList() {
    return $Call.ByID(3994622195).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType69($result);
    }));
}

/**
 * WorkflowRun executes a workflow YAML string and returns the report.
 * The YAML may be JSON as well (YAML superset). It is the desktop parity
 * for `reqly workflow <file>` and the Goja `reqly.workflow.run` binding.
 * @param {string} yamlStr
 * @returns {$CancellablePromise<workflow$0.WorkflowReport | null>}
 */
export function WorkflowRun(yamlStr) {
    return $Call.ByID(3138372844, yamlStr).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * WorkspaceCreate scaffolds a minimal Git-native workspace (descriptor plus
 * standard directories: collections/, environments/, tests/, .reqly/) at dir —
 * deriving the name from the folder when empty — then opens it. An existing descriptor is never touched.
 * @param {string} dir
 * @param {string} name
 * @returns {$CancellablePromise<core$0.WorkspaceTree | null>}
 */
export function WorkspaceCreate(dir, name) {
    return $Call.ByID(2642219307, dir, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType71($result);
    }));
}

/**
 * WorkspaceDuplicateRequest copies a request file in place as "<name> copy"
 * (file name suffixed -copy, -copy-2, …) and returns the refreshed tree plus
 * the copy's workspace-relative Request Path.
 * @param {string} path
 * @returns {$CancellablePromise<core$0.WorkspaceDuplicateResult | null>}
 */
export function WorkspaceDuplicateRequest(path) {
    return $Call.ByID(1515701461, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType73($result);
    }));
}

/**
 * WorkspaceLoad returns the workspace's collection tree (collections →
 * folders → requests, all name-sorted) with workspace-relative Request Paths.
 * A workspace without a collections/ directory yields an empty tree.
 * @returns {$CancellablePromise<core$0.WorkspaceTree | null>}
 */
export function WorkspaceLoad() {
    return $Call.ByID(3396669275).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType71($result);
    }));
}

/**
 * WorkspaceOpen switches every service to the workspace rooted at dir and
 * returns its collection tree. Non-workspace directories are rejected with
 * create guidance rather than silently scaffolded.
 * @param {string} dir
 * @returns {$CancellablePromise<core$0.WorkspaceTree | null>}
 */
export function WorkspaceOpen(dir) {
    return $Call.ByID(462515431, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType71($result);
    }));
}

/**
 * WorkspaceOpenRequest resolves a request file by its workspace-relative
 * Request Path into its fully resolved form (effective URL, merged headers,
 * inherited auth, variable chain, file environment), ready for the editor.
 * @param {string} path
 * @returns {$CancellablePromise<core$0.OpenedRequest | null>}
 */
export function WorkspaceOpenRequest(path) {
    return $Call.ByID(255155544, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType75($result);
    }));
}

/**
 * WorkspacePickFolder shows the native directory chooser and returns the raw
 * selection ("" when cancelled). The frontend decides what to do with it —
 * open an existing workspace, or offer to scaffold one.
 * @returns {$CancellablePromise<string>}
 */
export function WorkspacePickFolder() {
    return $Call.ByID(3213574430);
}

/**
 * WorkspaceRestoreLast reopens the persisted last workspace when it is still
 * valid, so a normally-launched app lands back where the user left off. A
 * missing or invalid stored path is a silent no-op returning current status.
 * @returns {$CancellablePromise<$models.WorkspaceStatusResponse | null>}
 */
export function WorkspaceRestoreLast() {
    return $Call.ByID(3138150683).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType77($result);
    }));
}

/**
 * WorkspaceRunCancel aborts the active run by id. It returns an error when
 * no run with that id is in flight.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function WorkspaceRunCancel(id) {
    return $Call.ByID(2875803806, id);
}

/**
 * WorkspaceRunCollection starts a collection run for the collection or folder
 * at the workspace-relative Request Path. env names the environment pill for
 * the run (empty → the workspace descriptor's active environment). The run
 * executes on a background goroutine: per-step results stream to the frontend
 * as reqly.run.<id>.step events and the final report as reqly.run.<id>.done.
 * Only one run may be active at a time.
 * @param {string} path
 * @param {string} env
 * @param {boolean} failFast
 * @returns {$CancellablePromise<string>}
 */
export function WorkspaceRunCollection(path, env, failFast) {
    return $Call.ByID(2529503040, path, env, failFast);
}

/**
 * WorkspaceSaveRequest persists a request file's editable builder fields back
 * to disk, preserving format and every non-editable field. expectedVersion
 * must match the file's on-disk fingerprint from OpenedRequest.Version; a
 * mismatch surfaces as a changed-on-disk conflict instead of clobbering the
 * external edit. The returned string is the new baseline version for the tab.
 * @param {string} path
 * @param {core$0.RequestSave} save
 * @param {string} expectedVersion
 * @returns {$CancellablePromise<string>}
 */
export function WorkspaceSaveRequest(path, save, expectedVersion) {
    return $Call.ByID(156168891, path, save, expectedVersion);
}

/**
 * WorkspaceStatus reports whether a workspace is currently open.
 * @returns {$CancellablePromise<$models.WorkspaceStatusResponse | null>}
 */
export function WorkspaceStatus() {
    return $Call.ByID(2975081517).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType77($result);
    }));
}

// Private type creation functions
const $$createType0 = audit$0.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = auth$0.Token.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AuthStatusResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = workflow$0.WorkflowReport.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = collab$0.Collaborator.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = history$0.Cookie.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = diffing$0.DiffResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.ResponseDiffResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.SpecDiffResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.DocsResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.CrossEnvGap.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.EnvDiffResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = core$0.EnvListResponse.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = core$0.Environment.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $models.EnvValidateResult.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $models.ExportResult.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = $Create.Array($Create.Any);
const $$createType33 = graphql$0.Schema.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = grpc$0.Result.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = grpc$0.Service.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = history$0.Entry.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = core$0.SendResponse.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = $Create.Nullable($$createType39);
const $$createType44 = $models.ImportResult.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = $models.JwtTokenView.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = $models.MockStatus.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = $models.OpenapiExploreResult.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = $models.OpenapiGenerateResult.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = $models.PerfRunResult.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = policy$0.Policy.createFrom;
const $$createType57 = rbac$0.RBAC.createFrom;
const $$createType58 = $models.RunExportResult.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = scim$0.User.createFrom;
const $$createType61 = $Create.Array($$createType60);
const $$createType62 = $models.TestFileContent.createFrom;
const $$createType63 = $Create.Nullable($$createType62);
const $$createType64 = $models.TestRunResult.createFrom;
const $$createType65 = $Create.Nullable($$createType64);
const $$createType66 = $models.TestFileRef.createFrom;
const $$createType67 = $Create.Array($$createType66);
const $$createType68 = theme$0.Theme.createFrom;
const $$createType69 = $Create.Array($$createType68);
const $$createType70 = core$0.WorkspaceTree.createFrom;
const $$createType71 = $Create.Nullable($$createType70);
const $$createType72 = core$0.WorkspaceDuplicateResult.createFrom;
const $$createType73 = $Create.Nullable($$createType72);
const $$createType74 = core$0.OpenedRequest.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = $models.WorkspaceStatusResponse.createFrom;
const $$createType77 = $Create.Nullable($$createType76);
