// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jsontext$0 from "../../../../../../encoding/json/jsontext/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diffing$0 from "../../../internal/diffing/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as environments$0 from "../../../internal/environments/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importer$0 from "../../../internal/importer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jwt$0 from "../../../internal/jwt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as openapi$0 from "../../../internal/openapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as perf$0 from "../../../internal/perf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../../internal/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as testing$0 from "../../../internal/testing/models.js";

/**
 * AuthStatusResponse is the bridge-friendly auth status: the active store
 * backend plus the masked cached tokens.
 */
export class AuthStatusResponse {
    /**
     * Creates a new AuthStatusResponse instance.
     * @param {Partial<AuthStatusResponse>} [$$source = {}] - The source object to create the AuthStatusResponse.
     */
    constructor($$source = {}) {
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {core$0.AuthTokenStatus[]}
             */
            this["tokens"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthStatusResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthStatusResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField1_0($$parsedSource["tokens"]);
        }
        return new AuthStatusResponse(/** @type {Partial<AuthStatusResponse>} */($$parsedSource));
    }
}

/**
 * CrossEnvGap reports one variable key whose presence is inconsistent across
 * environments — defined in some, missing in others.
 */
export class CrossEnvGap {
    /**
     * Creates a new CrossEnvGap instance.
     * @param {Partial<CrossEnvGap>} [$$source = {}] - The source object to create the CrossEnvGap.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("presentIn" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["presentIn"] = [];
        }
        if (!("missingIn" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["missingIn"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrossEnvGap instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CrossEnvGap}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presentIn" in $$parsedSource) {
            $$parsedSource["presentIn"] = $$createField1_0($$parsedSource["presentIn"]);
        }
        if ("missingIn" in $$parsedSource) {
            $$parsedSource["missingIn"] = $$createField2_0($$parsedSource["missingIn"]);
        }
        return new CrossEnvGap(/** @type {Partial<CrossEnvGap>} */($$parsedSource));
    }
}

/**
 * DocsFile is one generated Markdown file returned for preview.
 */
export class DocsFile {
    /**
     * Creates a new DocsFile instance.
     * @param {Partial<DocsFile>} [$$source = {}] - The source object to create the DocsFile.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocsFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocsFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocsFile(/** @type {Partial<DocsFile>} */($$parsedSource));
    }
}

/**
 * DocsGenerateRequest describes one docs generation run. Collections narrows
 * output to the named collections (empty → whole workspace). OutName
 * overrides the default directory base name.
 */
export class DocsGenerateRequest {
    /**
     * Creates a new DocsGenerateRequest instance.
     * @param {Partial<DocsGenerateRequest>} [$$source = {}] - The source object to create the DocsGenerateRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["collections"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["outName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocsGenerateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocsGenerateRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField0_0($$parsedSource["collections"]);
        }
        return new DocsGenerateRequest(/** @type {Partial<DocsGenerateRequest>} */($$parsedSource));
    }
}

/**
 * DocsResult reports where the docs landed plus their content so the panel
 * can preview and copy without a second file-read round trip.
 */
export class DocsResult {
    /**
     * Creates a new DocsResult instance.
     * @param {Partial<DocsResult>} [$$source = {}] - The source object to create the DocsResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("requestCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestCount"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {DocsFile[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocsResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        return new DocsResult(/** @type {Partial<DocsResult>} */($$parsedSource));
    }
}

/**
 * EnvDiffResult is the key-level diff of two named environments, with secret
 * values masked exactly like `reqly env diff`.
 */
export class EnvDiffResult {
    /**
     * Creates a new EnvDiffResult instance.
     * @param {Partial<EnvDiffResult>} [$$source = {}] - The source object to create the EnvDiffResult.
     */
    constructor($$source = {}) {
        if (!("envA" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envA"] = "";
        }
        if (!("envB" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["envB"] = "";
        }
        if (!("diffs" in $$source)) {
            /**
             * @member
             * @type {environments$0.KeyDiff[]}
             */
            this["diffs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvDiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvDiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diffs" in $$parsedSource) {
            $$parsedSource["diffs"] = $$createField2_0($$parsedSource["diffs"]);
        }
        return new EnvDiffResult(/** @type {Partial<EnvDiffResult>} */($$parsedSource));
    }
}

/**
 * EnvValidateResult carries one environment's validation findings.
 */
export class EnvValidateResult {
    /**
     * Creates a new EnvValidateResult instance.
     * @param {Partial<EnvValidateResult>} [$$source = {}] - The source object to create the EnvValidateResult.
     */
    constructor($$source = {}) {
        if (!("env" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["env"] = "";
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {environments$0.Issue[]}
             */
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvValidateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvValidateResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new EnvValidateResult(/** @type {Partial<EnvValidateResult>} */($$parsedSource));
    }
}

/**
 * ExportRequest describes one export. Format selects the target; Collection
 * narrows OpenAPI exports to a single collection (empty → whole workspace).
 * OutName overrides the generated file or directory base name.
 */
export class ExportRequest {
    /**
     * Creates a new ExportRequest instance.
     * @param {Partial<ExportRequest>} [$$source = {}] - The source object to create the ExportRequest.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["collection"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["outName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRequest(/** @type {Partial<ExportRequest>} */($$parsedSource));
    }
}

/**
 * ExportResult reports where the export landed and how much it carried.
 */
export class ExportResult {
    /**
     * Creates a new ExportResult instance.
     * @param {Partial<ExportResult>} [$$source = {}] - The source object to create the ExportResult.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["requestCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["entryCount"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult(/** @type {Partial<ExportResult>} */($$parsedSource));
    }
}

/**
 * GrpcInvokeRequest describes one call. The full request file model rides
 * along so auth/headers/grpc blocks behave exactly like a saved file.
 */
export class GrpcInvokeRequest {
    /**
     * Creates a new GrpcInvokeRequest instance.
     * @param {Partial<GrpcInvokeRequest>} [$$source = {}] - The source object to create the GrpcInvokeRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {request$0.Request}
             */
            this["request"] = (new request$0.Request());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrpcInvokeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GrpcInvokeRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField1_0($$parsedSource["request"]);
        }
        return new GrpcInvokeRequest(/** @type {Partial<GrpcInvokeRequest>} */($$parsedSource));
    }
}

/**
 * GrpcServicesRequest targets one endpoint for reflection discovery.
 */
export class GrpcServicesRequest {
    /**
     * Creates a new GrpcServicesRequest instance.
     * @param {Partial<GrpcServicesRequest>} [$$source = {}] - The source object to create the GrpcServicesRequest.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["protoFiles"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["tls"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrpcServicesRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GrpcServicesRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protoFiles" in $$parsedSource) {
            $$parsedSource["protoFiles"] = $$createField1_0($$parsedSource["protoFiles"]);
        }
        return new GrpcServicesRequest(/** @type {Partial<GrpcServicesRequest>} */($$parsedSource));
    }
}

/**
 * ImportRequest is the generic import ask. Content carries the raw payload
 * (file bytes or a pasted command); FormatHint overrides content-based
 * detection when non-empty; DryRun parses and previews without touching the
 * filesystem; TargetDir names the workspace folder created on commit
 * (empty → sanitized collection title).
 */
export class ImportRequest {
    /**
     * Creates a new ImportRequest instance.
     * @param {Partial<ImportRequest>} [$$source = {}] - The source object to create the ImportRequest.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["filename"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["formatHint"] = undefined;
        }
        if (!("dryRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dryRun"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportRequest(/** @type {Partial<ImportRequest>} */($$parsedSource));
    }
}

/**
 * ImportResult reports what an import produced or would produce. Report is
 * the structured M42 degradation record, rendered by the frontend grouped by
 * category with severity tallies.
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {importer$0.Format}
             */
            this["format"] = importer$0.Format.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (!("requestCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["environmentCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {importer$0.ImportReport | null | undefined}
             */
            this["report"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Operations carries the flattened OpenAPI operation list on dry-run so
             * the dialog can render a tag-grouped preview before commit.
             * @member
             * @type {openapi$0.Endpoint[] | undefined}
             */
            this["operations"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Request carries the parsed request for cURL imports (Kind "request").
             * @member
             * @type {request$0.Request | null | undefined}
             */
            this["request"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType13;
        const $$createField8_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField6_0($$parsedSource["report"]);
        }
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField7_0($$parsedSource["operations"]);
        }
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField8_0($$parsedSource["request"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * JwtClaim is one decoded claim rendered as a display string.
 */
export class JwtClaim {
    /**
     * Creates a new JwtClaim instance.
     * @param {Partial<JwtClaim>} [$$source = {}] - The source object to create the JwtClaim.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JwtClaim instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JwtClaim}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JwtClaim(/** @type {Partial<JwtClaim>} */($$parsedSource));
    }
}

/**
 * JwtTokenView is the inspector payload: claims flattened to display strings
 * (nested values are JSON-encoded) so the frontend never handles raw any.
 */
export class JwtTokenView {
    /**
     * Creates a new JwtTokenView instance.
     * @param {Partial<JwtTokenView>} [$$source = {}] - The source object to create the JwtTokenView.
     */
    constructor($$source = {}) {
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {JwtClaim[]}
             */
            this["header"] = [];
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {JwtClaim[]}
             */
            this["payload"] = [];
        }
        if (!("signature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signature"] = "";
        }
        if (!("alg" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alg"] = "";
        }
        if (!("expiry" in $$source)) {
            /**
             * @member
             * @type {jwt$0.ExpiryStatus}
             */
            this["expiry"] = (new jwt$0.ExpiryStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JwtTokenView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JwtTokenView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType16;
        const $$createField4_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("header" in $$parsedSource) {
            $$parsedSource["header"] = $$createField0_0($$parsedSource["header"]);
        }
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField1_0($$parsedSource["payload"]);
        }
        if ("expiry" in $$parsedSource) {
            $$parsedSource["expiry"] = $$createField4_0($$parsedSource["expiry"]);
        }
        return new JwtTokenView(/** @type {Partial<JwtTokenView>} */($$parsedSource));
    }
}

/**
 * MockRoute is one manually defined mock response edited in the panel.
 */
export class MockRoute {
    /**
     * Creates a new MockRoute instance.
     * @param {Partial<MockRoute>} [$$source = {}] - The source object to create the MockRoute.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["headers"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockRoute instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MockRoute}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField4_0($$parsedSource["headers"]);
        }
        return new MockRoute(/** @type {Partial<MockRoute>} */($$parsedSource));
    }
}

/**
 * MockStartRequest starts (or restarts) the workspace mock server.
 * SpecPath is an optional workspace-relative or absolute OpenAPI file;
 * routes are manual overrides served first. DelayMs adds latency to every
 * response; FailEvery simulates a 500 on every Nth request (0 disables).
 */
export class MockStartRequest {
    /**
     * Creates a new MockStartRequest instance.
     * @param {Partial<MockStartRequest>} [$$source = {}] - The source object to create the MockStartRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["specPath"] = undefined;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["delayMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["failEvery"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MockRoute[] | undefined}
             */
            this["routes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MockStartRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField4_0($$parsedSource["routes"]);
        }
        return new MockStartRequest(/** @type {Partial<MockStartRequest>} */($$parsedSource));
    }
}

/**
 * MockStatus reports whether the mock server is running, and where.
 */
export class MockStatus {
    /**
     * Creates a new MockStatus instance.
     * @param {Partial<MockStatus>} [$$source = {}] - The source object to create the MockStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MockStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MockStatus(/** @type {Partial<MockStatus>} */($$parsedSource));
    }
}

/**
 * OpenapiEndpoint is one explorer entry with inline schema views.
 */
export class OpenapiEndpoint {
    /**
     * Creates a new OpenapiEndpoint instance.
     * @param {Partial<OpenapiEndpoint>} [$$source = {}] - The source object to create the OpenapiEndpoint.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["operationId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * RequestSchema is the JSON-encoded request-body schema ("" when none).
             * @member
             * @type {string | undefined}
             */
            this["requestSchema"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ResponseSchemas maps status code → JSON-encoded response schema.
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["responseSchemas"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenapiEndpoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenapiEndpoint}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("responseSchemas" in $$parsedSource) {
            $$parsedSource["responseSchemas"] = $$createField6_0($$parsedSource["responseSchemas"]);
        }
        return new OpenapiEndpoint(/** @type {Partial<OpenapiEndpoint>} */($$parsedSource));
    }
}

/**
 * OpenapiExploreResult is the whole spec summary for the browser panel.
 */
export class OpenapiExploreResult {
    /**
     * Creates a new OpenapiExploreResult instance.
     * @param {Partial<OpenapiExploreResult>} [$$source = {}] - The source object to create the OpenapiExploreResult.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("endpoints" in $$source)) {
            /**
             * @member
             * @type {OpenapiEndpoint[]}
             */
            this["endpoints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["warnings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenapiExploreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenapiExploreResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType22;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField2_0($$parsedSource["endpoints"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new OpenapiExploreResult(/** @type {Partial<OpenapiExploreResult>} */($$parsedSource));
    }
}

/**
 * OpenapiGenerateResult reports where generated request files landed and how
 * many were created; Warnings carries per-operation skips.
 */
export class OpenapiGenerateResult {
    /**
     * Creates a new OpenapiGenerateResult instance.
     * @param {Partial<OpenapiGenerateResult>} [$$source = {}] - The source object to create the OpenapiGenerateResult.
     */
    constructor($$source = {}) {
        if (!("targetDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetDir"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["created"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["warnings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenapiGenerateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenapiGenerateResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("created" in $$parsedSource) {
            $$parsedSource["created"] = $$createField1_0($$parsedSource["created"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new OpenapiGenerateResult(/** @type {Partial<OpenapiGenerateResult>} */($$parsedSource));
    }
}

/**
 * OpenapiGenerateSelection is one operation to generate a request for.
 */
export class OpenapiGenerateSelection {
    /**
     * Creates a new OpenapiGenerateSelection instance.
     * @param {Partial<OpenapiGenerateSelection>} [$$source = {}] - The source object to create the OpenapiGenerateSelection.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenapiGenerateSelection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenapiGenerateSelection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenapiGenerateSelection(/** @type {Partial<OpenapiGenerateSelection>} */($$parsedSource));
    }
}

/**
 * PaginationConfig mirrors request.Pagination for the config panel.
 */
export class PaginationConfig {
    /**
     * Creates a new PaginationConfig instance.
     * @param {Partial<PaginationConfig>} [$$source = {}] - The source object to create the PaginationConfig.
     */
    constructor($$source = {}) {
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageSizeParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["offsetParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["limitParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cursorParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nextPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxPages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pageSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginationConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaginationConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaginationConfig(/** @type {Partial<PaginationConfig>} */($$parsedSource));
    }
}

/**
 * PerfRunResult is the bridge result for the desktop perf dashboard.
 */
export class PerfRunResult {
    /**
     * Creates a new PerfRunResult instance.
     * @param {Partial<PerfRunResult>} [$$source = {}] - The source object to create the PerfRunResult.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {perf$0.Result}
             */
            this["result"] = (new perf$0.Result());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PerfRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PerfRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new PerfRunResult(/** @type {Partial<PerfRunResult>} */($$parsedSource));
    }
}

/**
 * RealtimeHeader is one connection header (key/value pair from the dialog).
 */
export class RealtimeHeader {
    /**
     * Creates a new RealtimeHeader instance.
     * @param {Partial<RealtimeHeader>} [$$source = {}] - The source object to create the RealtimeHeader.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RealtimeHeader instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RealtimeHeader}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RealtimeHeader(/** @type {Partial<RealtimeHeader>} */($$parsedSource));
    }
}

/**
 * RealtimeOpenRequest starts a WebSocket ("ws") or Server-Sent Events
 * ("sse") session identified by SessionID — a frontend-generated id so the
 * webview can route streamed events to the right tab.
 */
export class RealtimeOpenRequest {
    /**
     * Creates a new RealtimeOpenRequest instance.
     * @param {Partial<RealtimeOpenRequest>} [$$source = {}] - The source object to create the RealtimeOpenRequest.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "ws" | "sse"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {RealtimeHeader[] | undefined}
             */
            this["headers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RealtimeOpenRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RealtimeOpenRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new RealtimeOpenRequest(/** @type {Partial<RealtimeOpenRequest>} */($$parsedSource));
    }
}

/**
 * ResponseDiffMeta describes one history entry compared in the diff view.
 */
export class ResponseDiffMeta {
    /**
     * Creates a new ResponseDiffMeta instance.
     * @param {Partial<ResponseDiffMeta>} [$$source = {}] - The source object to create the ResponseDiffMeta.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["env"] = undefined;
        }
        if (!("preview" in $$source)) {
            /**
             * truncated response body for side-by-side view
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponseDiffMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResponseDiffMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResponseDiffMeta(/** @type {Partial<ResponseDiffMeta>} */($$parsedSource));
    }
}

/**
 * ResponseDiffResult pairs structural changes with both entries' metadata.
 */
export class ResponseDiffResult {
    /**
     * Creates a new ResponseDiffResult instance.
     * @param {Partial<ResponseDiffResult>} [$$source = {}] - The source object to create the ResponseDiffResult.
     */
    constructor($$source = {}) {
        if (!("metaA" in $$source)) {
            /**
             * @member
             * @type {ResponseDiffMeta | null}
             */
            this["metaA"] = null;
        }
        if (!("metaB" in $$source)) {
            /**
             * @member
             * @type {ResponseDiffMeta | null}
             */
            this["metaB"] = null;
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {diffing$0.DiffResult | null}
             */
            this["result"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorA"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorB"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponseDiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResponseDiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType27;
        const $$createField1_0 = $$createType27;
        const $$createField2_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metaA" in $$parsedSource) {
            $$parsedSource["metaA"] = $$createField0_0($$parsedSource["metaA"]);
        }
        if ("metaB" in $$parsedSource) {
            $$parsedSource["metaB"] = $$createField1_0($$parsedSource["metaB"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField2_0($$parsedSource["result"]);
        }
        return new ResponseDiffResult(/** @type {Partial<ResponseDiffResult>} */($$parsedSource));
    }
}

/**
 * RunExportResult reports where the export landed plus its content so the
 * Run View can preview without re-reading the file.
 */
export class RunExportResult {
    /**
     * Creates a new RunExportResult instance.
     * @param {Partial<RunExportResult>} [$$source = {}] - The source object to create the RunExportResult.
     */
    constructor($$source = {}) {
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunExportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunExportResult(/** @type {Partial<RunExportResult>} */($$parsedSource));
    }
}

/**
 * RunReportExportInput is the finished run's aggregate, sent back by the
 * frontend when the user exports the report.
 */
export class RunReportExportInput {
    /**
     * Creates a new RunReportExportInput instance.
     * @param {Partial<RunReportExportInput>} [$$source = {}] - The source object to create the RunReportExportInput.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * collection/folder path (suite name)
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["started"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["finished"] = undefined;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {runReportStep[]}
             */
            this["steps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunReportExportInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunReportExportInput}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField4_0($$parsedSource["steps"]);
        }
        return new RunReportExportInput(/** @type {Partial<RunReportExportInput>} */($$parsedSource));
    }
}

/**
 * RunnerRunRequest drives both runner kinds from one draft payload; Kind
 * selects pagination vs bulk.
 */
export class RunnerRunRequest {
    /**
     * Creates a new RunnerRunRequest instance.
     * @param {Partial<RunnerRunRequest>} [$$source = {}] - The source object to create the RunnerRunRequest.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "pagination" | "bulk"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {json$0.RawMessage}
             */
            this["request"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PaginationConfig | undefined}
             */
            this["pagination"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxPagesOverride"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataFormat"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["parallel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["concurrency"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunnerRunRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunnerRunRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pagination" in $$parsedSource) {
            $$parsedSource["pagination"] = $$createField3_0($$parsedSource["pagination"]);
        }
        return new RunnerRunRequest(/** @type {Partial<RunnerRunRequest>} */($$parsedSource));
    }
}

/**
 * SendOptions carries the per-send environment pill plus, for file-backed
 * tabs, the request file's workspace-relative path. Env is the environment
 * pill (a request file's environment: field); when empty, the app's active
 * environment applies. When RequestPath is non-empty, the sent request is
 * treated as the tab's live draft and the full inheritance chain (base URL,
 * merged headers, inherited auth, variable scopes) is re-resolved against it
 * at send time; when empty, the request is sent as-is (scratchpad).
 */
export class SendOptions {
    /**
     * Creates a new SendOptions instance.
     * @param {Partial<SendOptions>} [$$source = {}] - The source object to create the SendOptions.
     */
    constructor($$source = {}) {
        if (!("env" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["env"] = "";
        }
        if (!("requestPath" in $$source)) {
            /**
             * RequestPath is the workspace-relative Request Path of the request file
             * this send belongs to (e.g. "users/auth/login").
             * @member
             * @type {string}
             */
            this["requestPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * SendID identifies an in-flight send so the UI can cancel it. When
             * non-empty, the send's context is cancellable via CancelSend; empty
             * means the send cannot be cancelled.
             * @member
             * @type {string | undefined}
             */
            this["sendId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendOptions(/** @type {Partial<SendOptions>} */($$parsedSource));
    }
}

/**
 * SpecDiffResult is the payload for the Specs tab of the diff view.
 */
export class SpecDiffResult {
    /**
     * Creates a new SpecDiffResult instance.
     * @param {Partial<SpecDiffResult>} [$$source = {}] - The source object to create the SpecDiffResult.
     */
    constructor($$source = {}) {
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {diffing$0.DiffResult | null}
             */
            this["result"] = null;
        }
        if (!("breaking" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["breaking"] = 0;
        }
        if (!("addition" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["addition"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpecDiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpecDiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new SpecDiffResult(/** @type {Partial<SpecDiffResult>} */($$parsedSource));
    }
}

/**
 * TestFileContent is a test file's raw text plus its detected format.
 */
export class TestFileContent {
    /**
     * Creates a new TestFileContent instance.
     * @param {Partial<TestFileContent>} [$$source = {}] - The source object to create the TestFileContent.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * "yaml" | "json"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestFileContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestFileContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestFileContent(/** @type {Partial<TestFileContent>} */($$parsedSource));
    }
}

/**
 * TestFileRef identifies one .reqly-test file in the workspace.
 */
export class TestFileRef {
    /**
     * Creates a new TestFileRef instance.
     * @param {Partial<TestFileRef>} [$$source = {}] - The source object to create the TestFileRef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * workspace-relative, forward slashes
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestFileRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestFileRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestFileRef(/** @type {Partial<TestFileRef>} */($$parsedSource));
    }
}

/**
 * TestRunRequest runs assertions from disk (Path) or from unsaved editor
 * text (Content wins when non-empty). Env optionally names an environment,
 * overridden by REQLY_ENV exactly like `reqly test --env`.
 */
export class TestRunRequest {
    /**
     * Creates a new TestRunRequest instance.
     * @param {Partial<TestRunRequest>} [$$source = {}] - The source object to create the TestRunRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["env"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestRunRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestRunRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestRunRequest(/** @type {Partial<TestRunRequest>} */($$parsedSource));
    }
}

/**
 * TestRunResult reports per-test assertion outcomes.
 */
export class TestRunResult {
    /**
     * Creates a new TestRunResult instance.
     * @param {Partial<TestRunResult>} [$$source = {}] - The source object to create the TestRunResult.
     */
    constructor($$source = {}) {
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("passCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passCount"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {testing$0.TestResult[]}
             */
            this["results"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestRunResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestRunResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField4_0($$parsedSource["results"]);
        }
        return new TestRunResult(/** @type {Partial<TestRunResult>} */($$parsedSource));
    }
}

/**
 * WorkspaceStatusResponse tells the frontend whether a workspace is open and
 * where it lives, so the UI can branch between normal operation and the
 * empty-state bootstrap flow at startup.
 */
export class WorkspaceStatusResponse {
    /**
     * Creates a new WorkspaceStatusResponse instance.
     * @param {Partial<WorkspaceStatusResponse>} [$$source = {}] - The source object to create the WorkspaceStatusResponse.
     */
    constructor($$source = {}) {
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceStatusResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceStatusResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceStatusResponse(/** @type {Partial<WorkspaceStatusResponse>} */($$parsedSource));
    }
}

/**
 * runReportStep mirrors the frontend RunStep for export purposes.
 */
export class runReportStep {
    /**
     * Creates a new runReportStep instance.
     * @param {Partial<runReportStep>} [$$source = {}] - The source object to create the runReportStep.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestPath"] = undefined;
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {runReportTest[] | undefined}
             */
            this["tests"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new runReportStep instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {runReportStep}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tests" in $$parsedSource) {
            $$parsedSource["tests"] = $$createField5_0($$parsedSource["tests"]);
        }
        return new runReportStep(/** @type {Partial<runReportStep>} */($$parsedSource));
    }
}

/**
 * runReportTest is one assertion outcome as streamed to the frontend.
 */
export class runReportTest {
    /**
     * Creates a new runReportTest instance.
     * @param {Partial<runReportTest>} [$$source = {}] - The source object to create the runReportTest.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new runReportTest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {runReportTest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new runReportTest(/** @type {Partial<runReportTest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = core$0.AuthTokenStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = DocsFile.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = environments$0.KeyDiff.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = environments$0.Issue.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = request$0.Request.createFrom;
const $$createType10 = importer$0.ImportReport.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = openapi$0.Endpoint.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Nullable($$createType9);
const $$createType15 = JwtClaim.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = jwt$0.ExpiryStatus.createFrom;
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = MockRoute.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = OpenapiEndpoint.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = perf$0.Result.createFrom;
const $$createType24 = RealtimeHeader.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = ResponseDiffMeta.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = diffing$0.DiffResult.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = runReportStep.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = PaginationConfig.createFrom;
const $$createType33 = testing$0.TestResult.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = runReportTest.createFrom;
const $$createType36 = $Create.Array($$createType35);
