// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Arg is one field argument.
 */
export class Arg {
    /**
     * Creates a new Arg instance.
     * @param {Partial<Arg>} [$$source = {}] - The source object to create the Arg.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TypeRef | null}
             */
            this["type"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * default value literal, "" when none
             * @member
             * @type {string | undefined}
             */
            this["def"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Arg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Arg}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type" in $$parsedSource) {
            $$parsedSource["type"] = $$createField1_0($$parsedSource["type"]);
        }
        return new Arg(/** @type {Partial<Arg>} */($$parsedSource));
    }
}

/**
 * Field is one object/interface field.
 */
export class Field {
    /**
     * Creates a new Field instance.
     * @param {Partial<Field>} [$$source = {}] - The source object to create the Field.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {TypeRef | null}
             */
            this["type"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Arg[] | undefined}
             */
            this["args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["deprecated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Field}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type" in $$parsedSource) {
            $$parsedSource["type"] = $$createField2_0($$parsedSource["type"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        return new Field(/** @type {Partial<Field>} */($$parsedSource));
    }
}

/**
 * Schema is an introspected GraphQL schema.
 */
export class Schema {
    /**
     * Creates a new Schema instance.
     * @param {Partial<Schema>} [$$source = {}] - The source object to create the Schema.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Type | null | undefined}
             */
            this["query"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Type | null | undefined}
             */
            this["mutation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Type | null | undefined}
             */
            this["subscription"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * non-builtin types, sorted by name
             * @member
             * @type {(Type | null)[] | undefined}
             */
            this["types"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Schema}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField0_0($$parsedSource["query"]);
        }
        if ("mutation" in $$parsedSource) {
            $$parsedSource["mutation"] = $$createField1_0($$parsedSource["mutation"]);
        }
        if ("subscription" in $$parsedSource) {
            $$parsedSource["subscription"] = $$createField2_0($$parsedSource["subscription"]);
        }
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField3_0($$parsedSource["types"]);
        }
        return new Schema(/** @type {Partial<Schema>} */($$parsedSource));
    }
}

/**
 * Type is a schema type (object, scalar, enum, interface, union, input).
 */
export class Type {
    /**
     * Creates a new Type instance.
     * @param {Partial<Type>} [$$source = {}] - The source object to create the Type.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * objects/interfaces only
             * @member
             * @type {Field[] | undefined}
             */
            this["fields"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["enumValues"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Type instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Type}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        if ("enumValues" in $$parsedSource) {
            $$parsedSource["enumValues"] = $$createField4_0($$parsedSource["enumValues"]);
        }
        return new Type(/** @type {Partial<Type>} */($$parsedSource));
    }
}

/**
 * TypeRef is a wrapped GraphQL type reference.
 */
export class TypeRef {
    /**
     * Creates a new TypeRef instance.
     * @param {Partial<TypeRef>} [$$source = {}] - The source object to create the TypeRef.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * set on named types
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * LIST / NON_NULL / named kind
             * @member
             * @type {string}
             */
            this["Kind"] = "";
        }
        if (!("Of" in $$source)) {
            /**
             * inner type for wrappers
             * @member
             * @type {TypeRef | null}
             */
            this["Of"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TypeRef}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Of" in $$parsedSource) {
            $$parsedSource["Of"] = $$createField2_0($$parsedSource["Of"]);
        }
        return new TypeRef(/** @type {Partial<TypeRef>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TypeRef.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Arg.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Type.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Field.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
