// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Cookie struct {
	Name      sql.NullString
	Value     sql.NullString
	Domain    sql.NullString
	Path      sql.NullString
	ExpiresAt string
	Secure    sql.NullInt64
	HttpOnly  sql.NullInt64
	SameSite  sql.NullString
	Env       sql.NullString
	CreatedAt string
}

type History struct {
	ID              string
	RequestPath     sql.NullString
	Method          sql.NullString
	Url             sql.NullString
	Env             sql.NullString
	Status          sql.NullInt64
	DurationMs      sql.NullInt64
	Size            sql.NullInt64
	ReqHeadersJson  sql.NullString
	ReqBody         []byte
	ReqBodyPath     sql.NullString
	RespHeadersJson sql.NullString
	RespBody        []byte
	RespBodyPath    sql.NullString
	Attempts        sql.NullInt64
	CreatedAt       string
}

type HistoryFt struct {
	Url         string
	RequestPath string
	ID          string
}
