// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAllCookies = `-- name: DeleteAllCookies :exec
DELETE FROM cookies
`

func (q *Queries) DeleteAllCookies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCookies)
	return err
}

const deleteAllHistory = `-- name: DeleteAllHistory :exec
DELETE FROM history
`

func (q *Queries) DeleteAllHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllHistory)
	return err
}

const deleteAllHistoryFts = `-- name: DeleteAllHistoryFts :exec
DELETE FROM history_fts
`

func (q *Queries) DeleteAllHistoryFts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllHistoryFts)
	return err
}

const deleteCookie = `-- name: DeleteCookie :exec
DELETE FROM cookies WHERE name = ? AND domain = ? AND path = ? AND env = ?
`

type DeleteCookieParams struct {
	Name   sql.NullString
	Domain sql.NullString
	Path   sql.NullString
	Env    sql.NullString
}

func (q *Queries) DeleteCookie(ctx context.Context, arg DeleteCookieParams) error {
	_, err := q.db.ExecContext(ctx, deleteCookie,
		arg.Name,
		arg.Domain,
		arg.Path,
		arg.Env,
	)
	return err
}

const deleteCookiesByEnv = `-- name: DeleteCookiesByEnv :exec
DELETE FROM cookies WHERE env = ?
`

func (q *Queries) DeleteCookiesByEnv(ctx context.Context, env sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCookiesByEnv, env)
	return err
}

const deleteHistoryById = `-- name: DeleteHistoryById :exec
DELETE FROM history WHERE id = ?
`

func (q *Queries) DeleteHistoryById(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryById, id)
	return err
}

const deleteHistoryFtsById = `-- name: DeleteHistoryFtsById :exec
DELETE FROM history_fts WHERE id = ?
`

func (q *Queries) DeleteHistoryFtsById(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHistoryFtsById, id)
	return err
}

const getHistory = `-- name: GetHistory :one
SELECT id, request_path, method, url, env, status, duration_ms, size,
       req_headers_json, req_body, req_body_path,
       resp_headers_json, resp_body, resp_body_path, attempts, created_at
FROM history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHistory(ctx context.Context, id string) (History, error) {
	row := q.db.QueryRowContext(ctx, getHistory, id)
	var i History
	err := row.Scan(
		&i.ID,
		&i.RequestPath,
		&i.Method,
		&i.Url,
		&i.Env,
		&i.Status,
		&i.DurationMs,
		&i.Size,
		&i.ReqHeadersJson,
		&i.ReqBody,
		&i.ReqBodyPath,
		&i.RespHeadersJson,
		&i.RespBody,
		&i.RespBodyPath,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO history (
    id, request_path, method, url, env, status, duration_ms, size,
    req_headers_json, req_body, req_body_path,
    resp_headers_json, resp_body, resp_body_path,
    attempts, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHistoryParams struct {
	ID              string
	RequestPath     sql.NullString
	Method          sql.NullString
	Url             sql.NullString
	Env             sql.NullString
	Status          sql.NullInt64
	DurationMs      sql.NullInt64
	Size            sql.NullInt64
	ReqHeadersJson  sql.NullString
	ReqBody         []byte
	ReqBodyPath     sql.NullString
	RespHeadersJson sql.NullString
	RespBody        []byte
	RespBodyPath    sql.NullString
	Attempts        sql.NullInt64
	CreatedAt       string
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.ID,
		arg.RequestPath,
		arg.Method,
		arg.Url,
		arg.Env,
		arg.Status,
		arg.DurationMs,
		arg.Size,
		arg.ReqHeadersJson,
		arg.ReqBody,
		arg.ReqBodyPath,
		arg.RespHeadersJson,
		arg.RespBody,
		arg.RespBodyPath,
		arg.Attempts,
		arg.CreatedAt,
	)
	return err
}

const insertHistoryFts = `-- name: InsertHistoryFts :exec
INSERT INTO history_fts (url, request_path, id) VALUES (?, ?, ?)
`

type InsertHistoryFtsParams struct {
	Url         string
	RequestPath string
	ID          string
}

func (q *Queries) InsertHistoryFts(ctx context.Context, arg InsertHistoryFtsParams) error {
	_, err := q.db.ExecContext(ctx, insertHistoryFts, arg.Url, arg.RequestPath, arg.ID)
	return err
}

const listCookiesByEnv = `-- name: ListCookiesByEnv :many
SELECT name, value, domain, path, expires_at, secure, http_only, same_site, env
FROM cookies WHERE env = ?
`

type ListCookiesByEnvRow struct {
	Name      sql.NullString
	Value     sql.NullString
	Domain    sql.NullString
	Path      sql.NullString
	ExpiresAt string
	Secure    sql.NullInt64
	HttpOnly  sql.NullInt64
	SameSite  sql.NullString
	Env       sql.NullString
}

func (q *Queries) ListCookiesByEnv(ctx context.Context, env sql.NullString) ([]ListCookiesByEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listCookiesByEnv, env)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCookiesByEnvRow
	for rows.Next() {
		var i ListCookiesByEnvRow
		if err := rows.Scan(
			&i.Name,
			&i.Value,
			&i.Domain,
			&i.Path,
			&i.ExpiresAt,
			&i.Secure,
			&i.HttpOnly,
			&i.SameSite,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT id, request_path, method, url, env, status, duration_ms, size,
       req_headers_json, req_body, req_body_path,
       resp_headers_json, resp_body, resp_body_path, attempts, created_at
FROM history
ORDER BY datetime(created_at) DESC
LIMIT ? OFFSET ?
`

type ListHistoryParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.RequestPath,
			&i.Method,
			&i.Url,
			&i.Env,
			&i.Status,
			&i.DurationMs,
			&i.Size,
			&i.ReqHeadersJson,
			&i.ReqBody,
			&i.ReqBodyPath,
			&i.RespHeadersJson,
			&i.RespBody,
			&i.RespBodyPath,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryIdsAsc = `-- name: ListHistoryIdsAsc :many
SELECT id FROM history ORDER BY datetime(created_at) ASC
`

func (q *Queries) ListHistoryIdsAsc(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryIdsAsc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryIdsByEnv = `-- name: ListHistoryIdsByEnv :many
SELECT id FROM history WHERE env = ?
`

func (q *Queries) ListHistoryIdsByEnv(ctx context.Context, env sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryIdsByEnv, env)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHistoryIds = `-- name: SearchHistoryIds :many
SELECT id FROM history_fts WHERE url MATCH ? OR request_path MATCH ? LIMIT ?
`

type SearchHistoryIdsParams struct {
	Url         string
	RequestPath string
	Limit       int64
}

func (q *Queries) SearchHistoryIds(ctx context.Context, arg SearchHistoryIdsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchHistoryIds, arg.Url, arg.RequestPath, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCookie = `-- name: UpsertCookie :exec
INSERT OR REPLACE INTO cookies (
    name, value, domain, path, expires_at, secure, http_only, same_site, env, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertCookieParams struct {
	Name      sql.NullString
	Value     sql.NullString
	Domain    sql.NullString
	Path      sql.NullString
	ExpiresAt string
	Secure    sql.NullInt64
	HttpOnly  sql.NullInt64
	SameSite  sql.NullString
	Env       sql.NullString
	CreatedAt string
}

func (q *Queries) UpsertCookie(ctx context.Context, arg UpsertCookieParams) error {
	_, err := q.db.ExecContext(ctx, upsertCookie,
		arg.Name,
		arg.Value,
		arg.Domain,
		arg.Path,
		arg.ExpiresAt,
		arg.Secure,
		arg.HttpOnly,
		arg.SameSite,
		arg.Env,
		arg.CreatedAt,
	)
	return err
}
