// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result is the summary after a perf run.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("rps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rps"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["latenciesMs"] = undefined;
        }
        if (!("p50Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p50Ms"] = 0;
        }
        if (!("p95Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p95Ms"] = 0;
        }
        if (!("p99Ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["p99Ms"] = 0;
        }
        if (!("statusCounts" in $$source)) {
            /**
             * @member
             * @type {{ [_ in `${number}`]?: number }}
             */
            this["statusCounts"] = {};
        }
        if (!("errorRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["errorRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latenciesMs" in $$parsedSource) {
            $$parsedSource["latenciesMs"] = $$createField3_0($$parsedSource["latenciesMs"]);
        }
        if ("statusCounts" in $$parsedSource) {
            $$parsedSource["statusCounts"] = $$createField7_0($$parsedSource["statusCounts"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
