// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Collaborator is a user with access to a shared workspace.
 */
export class Collaborator {
    /**
     * Creates a new Collaborator instance.
     * @param {Partial<Collaborator>} [$$source = {}] - The source object to create the Collaborator.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * viewer | editor | admin
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("addedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Collaborator instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Collaborator}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Collaborator(/** @type {Partial<Collaborator>} */($$parsedSource));
    }
}
