// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cookie is a persisted response cookie (Cookie Jar).
 */
export class Cookie {
    /**
     * Creates a new Cookie instance.
     * @param {Partial<Cookie>} [$$source = {}] - The source object to create the Cookie.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Value"] = "";
        }
        if (!("Domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Domain"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("ExpiresAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ExpiresAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("Secure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Secure"] = false;
        }
        if (!("HttpOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HttpOnly"] = false;
        }
        if (!("SameSite" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SameSite"] = "";
        }
        if (!("Env" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Env"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cookie instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cookie}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cookie(/** @type {Partial<Cookie>} */($$parsedSource));
    }
}

/**
 * Entry is one row in the per-workspace history, as defined in CONTEXT.md.
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("RequestPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RequestPath"] = "";
        }
        if (!("Method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Method"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("Env" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Env"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Status"] = 0;
        }
        if (!("DurationMS" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DurationMS"] = 0;
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }
        if (!("ReqHeaders" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["ReqHeaders"] = {};
        }
        if (!("ReqBody" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ReqBody"] = "";
        }
        if (!("RespHeaders" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["RespHeaders"] = {};
        }
        if (!("RespBody" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RespBody"] = "";
        }
        if (!("Attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Attempts"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $Create.ByteSlice;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ReqHeaders" in $$parsedSource) {
            $$parsedSource["ReqHeaders"] = $$createField8_0($$parsedSource["ReqHeaders"]);
        }
        if ("ReqBody" in $$parsedSource) {
            $$parsedSource["ReqBody"] = $$createField9_0($$parsedSource["ReqBody"]);
        }
        if ("RespHeaders" in $$parsedSource) {
            $$parsedSource["RespHeaders"] = $$createField10_0($$parsedSource["RespHeaders"]);
        }
        if ("RespBody" in $$parsedSource) {
            $$parsedSource["RespBody"] = $$createField11_0($$parsedSource["RespBody"]);
        }
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
