// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Auth describes the authentication configuration attached to a request.
 * Implementations live in the auth package and are dispatched by type.
 */
export class Auth {
    /**
     * Creates a new Auth instance.
     * @param {Partial<Auth>} [$$source = {}] - The source object to create the Auth.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Auth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Auth}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new Auth(/** @type {Partial<Auth>} */($$parsedSource));
    }
}

/**
 * GRPC configures one gRPC call (ADR 0028). Service/Method address the call
 * ("/package.Service/Method"); Message holds canonical-JSON; Timeout is a Go
 * duration string ("30s"); ProtoFiles are workspace-relative fallback schemas
 * for reflection-disabled servers.
 */
export class GRPC {
    /**
     * Creates a new GRPC instance.
     * @param {Partial<GRPC>} [$$source = {}] - The source object to create the GRPC.
     */
    constructor($$source = {}) {
        if (!("service" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["service"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["protoFiles"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Transport (M43 T4): plaintext h2c by default; TLS enables TLS against
             * system roots or CAFile, optionally skipping verification.
             * @member
             * @type {boolean | undefined}
             */
            this["tls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["tlsSkipVerify"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPC instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPC}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protoFiles" in $$parsedSource) {
            $$parsedSource["protoFiles"] = $$createField4_0($$parsedSource["protoFiles"]);
        }
        return new GRPC(/** @type {Partial<GRPC>} */($$parsedSource));
    }
}

/**
 * Header is a single request header.
 */
export class Header {
    /**
     * Creates a new Header instance.
     * @param {Partial<Header>} [$$source = {}] - The source object to create the Header.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Header instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Header}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Header(/** @type {Partial<Header>} */($$parsedSource));
    }
}

/**
 * Method is an HTTP method.
 * @readonly
 * @enum {string}
 */
export const Method = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MethodGet: "GET",
    MethodPost: "POST",
    MethodPut: "PUT",
    MethodPatch: "PATCH",
    MethodDelete: "DELETE",
    MethodHead: "HEAD",
    MethodOptions: "OPTIONS",
};

/**
 * Pagination configures iterative fetching for a paginated endpoint.
 */
export class Pagination {
    /**
     * Creates a new Pagination instance.
     * @param {Partial<Pagination>} [$$source = {}] - The source object to create the Pagination.
     */
    constructor($$source = {}) {
        if (!("strategy" in $$source)) {
            /**
             * page|offset|cursor|link-header
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pageSizeParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["offsetParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["limitParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cursorParam"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nextPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxPages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pageSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pagination instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Pagination}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pagination(/** @type {Partial<Pagination>} */($$parsedSource));
    }
}

/**
 * Parameter is a query or path parameter.
 */
export class Parameter {
    /**
     * Creates a new Parameter instance.
     * @param {Partial<Parameter>} [$$source = {}] - The source object to create the Parameter.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Parameter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Parameter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Parameter(/** @type {Partial<Parameter>} */($$parsedSource));
    }
}

/**
 * Request defines a single API request. The engine layer (transport, protocol
 * dispatch, authentication, variable interpolation, scripting) builds on this
 * definition.
 * 
 * The transport remains abstract so additional protocols (WebSocket, gRPC,
 * SSE, MQTT, ...) can be added without changing the application architecture.
 */
export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Method | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Header[] | undefined}
             */
            this["headers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Parameter[] | undefined}
             */
            this["query"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Auth | undefined}
             */
            this["auth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Pagination | null | undefined}
             */
            this["pagination"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Retry | null | undefined}
             */
            this["retry"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * milliseconds; 0 means "no explicit timeout"
             * @member
             * @type {number | undefined}
             */
            this["timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FollowRedirects overrides the default follow behavior when explicitly
             * false: the first response is returned as-is (3xx and all). nil keeps
             * the standard net/http follow behavior.
             * @member
             * @type {boolean | null | undefined}
             */
            this["followRedirects"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Proxy is an optional per-request proxy URL (http://proxy:8080). When set it
             * overrides ProxyFromEnvironment for this send; empty means environment proxy.
             * @member
             * @type {string | undefined}
             */
            this["proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLS configures per-request TLS (M47). When nil, system roots are used.
             * @member
             * @type {TLSConfig | null | undefined}
             */
            this["tls"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HTTPVersion configures protocol negotiation ("auto", "http1.1", "http2", "http3") (M56).
             * @member
             * @type {string | undefined}
             */
            this["httpVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DisableKeepAlives disables HTTP connection pooling per-request (M56).
             * @member
             * @type {boolean | undefined}
             */
            this["disableKeepAlives"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * GRPC configures a gRPC call (M43). When set, url carries host:port,
             * headers act as metadata, and body is ignored in favor of Message.
             * @member
             * @type {GRPC | null | undefined}
             */
            this["grpc"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType10;
        const $$createField13_0 = $$createType12;
        const $$createField16_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField4_0($$parsedSource["headers"]);
        }
        if ("query" in $$parsedSource) {
            $$parsedSource["query"] = $$createField5_0($$parsedSource["query"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField7_0($$parsedSource["auth"]);
        }
        if ("pagination" in $$parsedSource) {
            $$parsedSource["pagination"] = $$createField8_0($$parsedSource["pagination"]);
        }
        if ("retry" in $$parsedSource) {
            $$parsedSource["retry"] = $$createField9_0($$parsedSource["retry"]);
        }
        if ("tls" in $$parsedSource) {
            $$parsedSource["tls"] = $$createField13_0($$parsedSource["tls"]);
        }
        if ("grpc" in $$parsedSource) {
            $$parsedSource["grpc"] = $$createField16_0($$parsedSource["grpc"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

/**
 * Retry configures automatic re-sending of a failed request. Count is the
 * number of retries after the initial attempt; a nil Retry or Count <= 0
 * disables retrying entirely.
 */
export class Retry {
    /**
     * Creates a new Retry instance.
     * @param {Partial<Retry>} [$$source = {}] - The source object to create the Retry.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["delayMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * fixed | exponential
             * @member
             * @type {string | undefined}
             */
            this["strategy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxDelayMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["retryOn"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Retry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Retry}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("retryOn" in $$parsedSource) {
            $$parsedSource["retryOn"] = $$createField4_0($$parsedSource["retryOn"]);
        }
        return new Retry(/** @type {Partial<Retry>} */($$parsedSource));
    }
}

/**
 * TLSConfig configures per-request TLS (M47).
 */
export class TLSConfig {
    /**
     * Creates a new TLSConfig instance.
     * @param {Partial<TLSConfig>} [$$source = {}] - The source object to create the TLSConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["insecureSkipVerify"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["caFile"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TLSConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TLSConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TLSConfig(/** @type {Partial<TLSConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Header.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Parameter.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Auth.createFrom;
const $$createType7 = Pagination.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = Retry.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = TLSConfig.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = GRPC.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($Create.Any);
