// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as response$0 from "../response/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * StepResult records the outcome of one workflow step.
 */
export class StepResult {
    /**
     * Creates a new StepResult instance.
     * @param {Partial<StepResult>} [$$source = {}] - The source object to create the StepResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("requestPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestPath"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["requestError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {response$0.Response | null | undefined}
             */
            this["response"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField4_0($$parsedSource["response"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField5_0($$parsedSource["logs"]);
        }
        return new StepResult(/** @type {Partial<StepResult>} */($$parsedSource));
    }
}

/**
 * WorkflowReport summarizes the execution of a visual workflow.
 */
export class WorkflowReport {
    /**
     * Creates a new WorkflowReport instance.
     * @param {Partial<WorkflowReport>} [$$source = {}] - The source object to create the WorkflowReport.
     */
    constructor($$source = {}) {
        if (!("workflowName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflowName"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["duration"] = time$0.Duration.$zero;
        }
        if (!("steps" in $$source)) {
            /**
             * @member
             * @type {StepResult[]}
             */
            this["steps"] = [];
        }
        if (!("extractedVars" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["extractedVars"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkflowReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkflowReport}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField3_0($$parsedSource["steps"]);
        }
        if ("extractedVars" in $$parsedSource) {
            $$parsedSource["extractedVars"] = $$createField4_0($$parsedSource["extractedVars"]);
        }
        return new WorkflowReport(/** @type {Partial<WorkflowReport>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = response$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = StepResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
