// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Method describes one method of a discovered service.
 */
export class Method {
    /**
     * Creates a new Method instance.
     * @param {Partial<Method>} [$$source = {}] - The source object to create the Method.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Name is the method name without the service prefix ("Echo").
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("fullName" in $$source)) {
            /**
             * FullName is "/package.Service/Name", the address a call targets.
             * @member
             * @type {string}
             */
            this["fullName"] = "";
        }
        if (!("inputType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputType"] = "";
        }
        if (!("outputType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputType"] = "";
        }
        if (!("serverStreaming" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serverStreaming"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Method instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Method}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Method(/** @type {Partial<Method>} */($$parsedSource));
    }
}

/**
 * Result reports one completed unary call. OK is false when the server
 * returned a non-OK status; then Code/CodeName/StatusMessage carry the
 * failure and MessageJSON is empty.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageJson"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["code"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["codeName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["statusMessage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(StatusDetail | null)[] | undefined}
             */
            this["statusDetails"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messageJson" in $$parsedSource) {
            $$parsedSource["messageJson"] = $$createField0_0($$parsedSource["messageJson"]);
        }
        if ("statusDetails" in $$parsedSource) {
            $$parsedSource["statusDetails"] = $$createField6_0($$parsedSource["statusDetails"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * Service is one discovered gRPC service.
 */
export class Service {
    /**
     * Creates a new Service instance.
     * @param {Partial<Service>} [$$source = {}] - The source object to create the Service.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * fully-qualified "package.Service"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("methods" in $$source)) {
            /**
             * @member
             * @type {Method[]}
             */
            this["methods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Service}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField1_0($$parsedSource["methods"]);
        }
        return new Service(/** @type {Partial<Service>} */($$parsedSource));
    }
}

/**
 * StatusDetail is one error detail entry from a non-OK status.
 */
export class StatusDetail {
    /**
     * Creates a new StatusDetail instance.
     * @param {Partial<StatusDetail>} [$$source = {}] - The source object to create the StatusDetail.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusDetail(/** @type {Partial<StatusDetail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = StatusDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Method.createFrom;
const $$createType4 = $Create.Array($$createType3);
