// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Policy is a local organization policy file (e.g. .reqly/policy.yaml, 0600).
 * It is Git-native when committed, but the file itself is 0600 for secrets.
 * Policies are local-only, zero telemetry, and enforced by the core before
 * sensitive actions.
 */
export class Policy {
    /**
     * Creates a new Policy instance.
     * @param {Partial<Policy>} [$$source = {}] - The source object to create the Policy.
     */
    constructor($$source = {}) {
        if (!("requireAudit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requireAudit"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["maxWorkflowSteps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowedActions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requireAuth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["allowCustomThemes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Policy}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedActions" in $$parsedSource) {
            $$parsedSource["allowedActions"] = $$createField2_0($$parsedSource["allowedActions"]);
        }
        return new Policy(/** @type {Partial<Policy>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
