// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one audit trail record. Stored as JSONL in .reqly/audit.log (0600).
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("actor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["actor"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("resource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resource"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}
