// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../request/models.js";

/**
 * AuthTokenStatus is the masked, UI-friendly view of one cached token.
 */
export class AuthTokenStatus {
    /**
     * Creates a new AuthTokenStatus instance.
     * @param {Partial<AuthTokenStatus>} [$$source = {}] - The source object to create the AuthTokenStatus.
     */
    constructor($$source = {}) {
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("grantType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["grantType"] = "";
        }
        if (!("expiry" in $$source)) {
            /**
             * RFC3339, or "" when unknown
             * @member
             * @type {string}
             */
            this["expiry"] = "";
        }
        if (!("accessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accessToken"] = "";
        }
        if (!("hasRefresh" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasRefresh"] = false;
        }
        if (!("state" in $$source)) {
            /**
             * "cached" | "expired"
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthTokenStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthTokenStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthTokenStatus(/** @type {Partial<AuthTokenStatus>} */($$parsedSource));
    }
}

/**
 * EnvListResponse is the result of listing a workspace's environments plus
 * the currently active one.
 */
export class EnvListResponse {
    /**
     * Creates a new EnvListResponse instance.
     * @param {Partial<EnvListResponse>} [$$source = {}] - The source object to create the EnvListResponse.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["active"] = "";
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {Environment[]}
             */
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvListResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvListResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new EnvListResponse(/** @type {Partial<EnvListResponse>} */($$parsedSource));
    }
}

/**
 * Environment is the bridge-friendly view of an environment: its variables
 * and the *names* of its secrets. Secret values never cross the service
 * boundary — they stay on disk and are only written, never read back.
 */
export class Environment {
    /**
     * Creates a new Environment instance.
     * @param {Partial<Environment>} [$$source = {}] - The source object to create the Environment.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["variables"] = {};
        }
        if (!("secrets" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["secrets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Environment}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField2_0($$parsedSource["variables"]);
        }
        if ("secrets" in $$parsedSource) {
            $$parsedSource["secrets"] = $$createField3_0($$parsedSource["secrets"]);
        }
        return new Environment(/** @type {Partial<Environment>} */($$parsedSource));
    }
}

/**
 * OpenedRequest is a request file combined with its inherited configuration
 * and full variable chain, ready to be loaded into an editor. Placeholders
 * are left intact — they resolve at send time with the environment layer.
 */
export class OpenedRequest {
    /**
     * Creates a new OpenedRequest instance.
     * @param {Partial<OpenedRequest>} [$$source = {}] - The source object to create the OpenedRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {request$0.Request}
             */
            this["request"] = (new request$0.Request());
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {ResolvedVariable[]}
             */
            this["variables"] = [];
        }
        if (!("fileEnv" in $$source)) {
            /**
             * FileEnv is the request file's environment: field ("" when unset); the
             * sending tab uses it as its environment pill.
             * @member
             * @type {string}
             */
            this["fileEnv"] = "";
        }
        if (!("fileRequest" in $$source)) {
            /**
             * FileRequest is the raw, unmerged file-owned request: the editor seed.
             * It carries only what the file declares (no inherited base URL, headers,
             * or auth), and its builder fields (url/method/headers/query/body) plus its
             * own auth are editable — everything else is preserved verbatim on save.
             * @member
             * @type {request$0.Request}
             */
            this["fileRequest"] = (new request$0.Request());
        }
        if (!("preRequest" in $$source)) {
            /**
             * PreRequest/PostRequest are the file's sandbox scripts, editable in the
             * builder's Scripts tab and persisted verbatim on save.
             * @member
             * @type {string}
             */
            this["preRequest"] = "";
        }
        if (!("postRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postRequest"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * Version fingerprints the raw file bytes at open time. A save is only
             * accepted when the on-disk bytes still match; otherwise the request
             * changed under the editor and SaveRequest returns ErrFileChangedOnDisk.
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenedRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenedRequest}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField2_0($$parsedSource["request"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField3_0($$parsedSource["variables"]);
        }
        if ("fileRequest" in $$parsedSource) {
            $$parsedSource["fileRequest"] = $$createField5_0($$parsedSource["fileRequest"]);
        }
        return new OpenedRequest(/** @type {Partial<OpenedRequest>} */($$parsedSource));
    }
}

/**
 * RequestSave is the editable payload for SaveRequest: the builder's request
 * draft plus the file's sandbox scripts (Scripts tab).
 */
export class RequestSave {
    /**
     * Creates a new RequestSave instance.
     * @param {Partial<RequestSave>} [$$source = {}] - The source object to create the RequestSave.
     */
    constructor($$source = {}) {
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {request$0.Request}
             */
            this["draft"] = (new request$0.Request());
        }
        if (!("preRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preRequest"] = "";
        }
        if (!("postRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postRequest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestSave instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestSave}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField0_0($$parsedSource["draft"]);
        }
        return new RequestSave(/** @type {Partial<RequestSave>} */($$parsedSource));
    }
}

/**
 * ResolvedVariable is one entry of an opened request's effective variable
 * chain, tagged with the scope that defined it.
 */
export class ResolvedVariable {
    /**
     * Creates a new ResolvedVariable instance.
     * @param {Partial<ResolvedVariable>} [$$source = {}] - The source object to create the ResolvedVariable.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedVariable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolvedVariable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvedVariable(/** @type {Partial<ResolvedVariable>} */($$parsedSource));
    }
}

/**
 * SendResponse is the bridge-friendly result of executing a request. It uses
 * plain JSON-friendly types so Wails and other front-ends can marshal it
 * without special handling.
 */
export class SendResponse {
    /**
     * Creates a new SendResponse instance.
     * @param {Partial<SendResponse>} [$$source = {}] - The source object to create the SendResponse.
     */
    constructor($$source = {}) {
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("proto" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proto"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("attempts" in $$source)) {
            /**
             * Attempts reports how many sends the response took, including retries
             * (1 = no retry).
             * @member
             * @type {number}
             */
            this["attempts"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Timings | null | undefined}
             */
            this["timings"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResponse}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        if ("timings" in $$parsedSource) {
            $$parsedSource["timings"] = $$createField9_0($$parsedSource["timings"]);
        }
        return new SendResponse(/** @type {Partial<SendResponse>} */($$parsedSource));
    }
}

/**
 * Timings mirrors response.Timings for the bridge.
 */
export class Timings {
    /**
     * Creates a new Timings instance.
     * @param {Partial<Timings>} [$$source = {}] - The source object to create the Timings.
     */
    constructor($$source = {}) {
        if (!("dns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dns"] = 0;
        }
        if (!("connect" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connect"] = 0;
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tls"] = 0;
        }
        if (!("request" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["request"] = 0;
        }
        if (!("server" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["server"] = 0;
        }
        if (!("response" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["response"] = 0;
        }
        if (!("transfer" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["transfer"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Timings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Timings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Timings(/** @type {Partial<Timings>} */($$parsedSource));
    }
}

/**
 * WorkspaceCollection is a top-level collection of folders and requests.
 */
export class WorkspaceCollection {
    /**
     * Creates a new WorkspaceCollection instance.
     * @param {Partial<WorkspaceCollection>} [$$source = {}] - The source object to create the WorkspaceCollection.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("folders" in $$source)) {
            /**
             * @member
             * @type {WorkspaceFolder[]}
             */
            this["folders"] = [];
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {WorkspaceRequest[]}
             */
            this["requests"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceCollection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceCollection}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField2_0($$parsedSource["folders"]);
        }
        if ("requests" in $$parsedSource) {
            $$parsedSource["requests"] = $$createField3_0($$parsedSource["requests"]);
        }
        return new WorkspaceCollection(/** @type {Partial<WorkspaceCollection>} */($$parsedSource));
    }
}

/**
 * WorkspaceDuplicateResult pairs a refreshed workspace tree with the Request
 * Path of the newly duplicated request file.
 */
export class WorkspaceDuplicateResult {
    /**
     * Creates a new WorkspaceDuplicateResult instance.
     * @param {Partial<WorkspaceDuplicateResult>} [$$source = {}] - The source object to create the WorkspaceDuplicateResult.
     */
    constructor($$source = {}) {
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {WorkspaceTree | null}
             */
            this["tree"] = null;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDuplicateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceDuplicateResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField0_0($$parsedSource["tree"]);
        }
        return new WorkspaceDuplicateResult(/** @type {Partial<WorkspaceDuplicateResult>} */($$parsedSource));
    }
}

/**
 * WorkspaceFolder is a nested container (recursively) within a collection.
 */
export class WorkspaceFolder {
    /**
     * Creates a new WorkspaceFolder instance.
     * @param {Partial<WorkspaceFolder>} [$$source = {}] - The source object to create the WorkspaceFolder.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("folders" in $$source)) {
            /**
             * @member
             * @type {WorkspaceFolder[]}
             */
            this["folders"] = [];
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {WorkspaceRequest[]}
             */
            this["requests"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceFolder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceFolder}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField2_0($$parsedSource["folders"]);
        }
        if ("requests" in $$parsedSource) {
            $$parsedSource["requests"] = $$createField3_0($$parsedSource["requests"]);
        }
        return new WorkspaceFolder(/** @type {Partial<WorkspaceFolder>} */($$parsedSource));
    }
}

/**
 * WorkspaceRequest is a request file within a collection or folder, located
 * by its workspace-relative Request Path (e.g. "users/auth/login").
 */
export class WorkspaceRequest {
    /**
     * Creates a new WorkspaceRequest instance.
     * @param {Partial<WorkspaceRequest>} [$$source = {}] - The source object to create the WorkspaceRequest.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceRequest(/** @type {Partial<WorkspaceRequest>} */($$parsedSource));
    }
}

/**
 * WorkspaceTree is the bridge-friendly view of a workspace's collection
 * hierarchy: collections → folders → requests, all name-sorted.
 */
export class WorkspaceTree {
    /**
     * Creates a new WorkspaceTree instance.
     * @param {Partial<WorkspaceTree>} [$$source = {}] - The source object to create the WorkspaceTree.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("collections" in $$source)) {
            /**
             * @member
             * @type {WorkspaceCollection[]}
             */
            this["collections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTree instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceTree}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("collections" in $$parsedSource) {
            $$parsedSource["collections"] = $$createField2_0($$parsedSource["collections"]);
        }
        return new WorkspaceTree(/** @type {Partial<WorkspaceTree>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Environment.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = request$0.Request.createFrom;
const $$createType5 = ResolvedVariable.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $$createType3);
const $$createType8 = Timings.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = WorkspaceFolder.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = WorkspaceRequest.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = WorkspaceTree.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = WorkspaceCollection.createFrom;
const $$createType17 = $Create.Array($$createType16);
