// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Assertion is a single check evaluated against a response.
 */
export class Assertion {
    /**
     * Creates a new Assertion instance.
     * @param {Partial<Assertion>} [$$source = {}] - The source object to create the Assertion.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {AssertionKind}
             */
            this["kind"] = AssertionKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Path is a JSONPath for AssertJSONPath, or a header name for AssertHeader.
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Value is the expected string value (header value, body substring, or the
             * JSON value rendered as text when StringEquals is set).
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Expected is the expected number for status / response_time assertions,
             * and the expected JSON value (when JSON is used as a number).
             * @member
             * @type {number | undefined}
             */
            this["expected"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Exact makes AssertJSONPath compare the extracted value as a string
             * instead of only checking presence.
             * @member
             * @type {boolean | undefined}
             */
            this["exact"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Not inverts the assertion result.
             * @member
             * @type {boolean | undefined}
             */
            this["not"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assertion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Assertion}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Assertion(/** @type {Partial<Assertion>} */($$parsedSource));
    }
}

/**
 * AssertionKind identifies what aspect of a response an assertion checks.
 * @readonly
 * @enum {string}
 */
export const AssertionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * AssertStatus checks the HTTP status code.
     */
    AssertStatus: "status",

    /**
     * AssertHeader checks a response header exists (and optionally its value).
     */
    AssertHeader: "header",

    /**
     * AssertBodyContains checks the raw body contains a substring.
     */
    AssertBodyContains: "body_contains",

    /**
     * AssertBodyEquals checks the raw body equals a string exactly.
     */
    AssertBodyEquals: "body_equals",

    /**
     * AssertJSONPath checks a value extracted from a JSON body at a JSONPath.
     */
    AssertJSONPath: "json",

    /**
     * AssertResponseTime checks the request duration against a threshold (ms).
     */
    AssertResponseTime: "response_time",

    /**
     * AssertJSONSchema validates the response body against a JSON Schema file.
     */
    AssertJSONSchema: "json_schema",
};

/**
 * Result records the outcome of a single assertion.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("assertion" in $$source)) {
            /**
             * @member
             * @type {Assertion}
             */
            this["assertion"] = (new Assertion());
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assertion" in $$parsedSource) {
            $$parsedSource["assertion"] = $$createField0_0($$parsedSource["assertion"]);
        }
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * TestResult records the outcome of a single test.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {Result[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField2_0($$parsedSource["results"]);
        }
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Assertion.createFrom;
const $$createType1 = Result.createFrom;
const $$createType2 = $Create.Array($$createType1);
